/*
ArborXR MDM API

Testing HeadsetExperienceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package arborapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/heru-inc/arbor-api-go"
)

func Test_arborapi_HeadsetExperienceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HeadsetExperienceAPIService ConfigureDeviceArborXrHomeHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var deviceId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureDeviceArborXrHomeHeadsetExperience(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService ConfigureDeviceArborXrKioskHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var deviceId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureDeviceArborXrKioskHeadsetExperience(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService ConfigureDeviceDefaultHomeHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var deviceId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureDeviceDefaultHomeHeadsetExperience(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService ConfigureDeviceInHouseLauncherHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var deviceId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureDeviceInHouseLauncherHeadsetExperience(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService ConfigureGroupArborXrHomeHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureGroupArborXrHomeHeadsetExperience(context.Background(), groupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService ConfigureGroupArborXrKioskHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureGroupArborXrKioskHeadsetExperience(context.Background(), groupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService ConfigureGroupDefaultHomeHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureGroupDefaultHomeHeadsetExperience(context.Background(), groupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService ConfigureGroupInHouseLauncherHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		httpRes, err := apiClient.HeadsetExperienceAPI.ConfigureGroupInHouseLauncherHeadsetExperience(context.Background(), groupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService GetDeviceHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var deviceId string

		resp, httpRes, err := apiClient.HeadsetExperienceAPI.GetDeviceHeadsetExperience(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HeadsetExperienceAPIService GetGroupHeadsetExperience", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.HeadsetExperienceAPI.GetGroupHeadsetExperience(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
