/*
ArborXR MDM API

Testing InsightsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package arborapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/heru-inc/arbor-api-go"
)

func Test_arborapi_InsightsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InsightsAPIService QueryInsightsData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var insightsAppId string

		resp, httpRes, err := apiClient.InsightsAPI.QueryInsightsData(context.Background(), insightsAppId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
