/*
ArborXR MDM API

Testing VideosAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package arborapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/heru-inc/arbor-api-go"
)

func Test_arborapi_VideosAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VideosAPIService AttachTagsToVideo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		httpRes, err := apiClient.VideosAPI.AttachTagsToVideo(context.Background(), videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService CompleteVideoUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.CompleteVideoUpload(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DeleteVideo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		httpRes, err := apiClient.VideosAPI.DeleteVideo(context.Background(), videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService DetachTagsFromVideo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		httpRes, err := apiClient.VideosAPI.DetachTagsFromVideo(context.Background(), videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService GetVideo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.GetVideo(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService GetVideoDeviceStatuses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.GetVideoDeviceStatuses(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService GetVideos", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.GetVideos(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService InitiateVideoUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VideosAPI.InitiateVideoUpload(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService PreSignVideoUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.PreSignVideoUpload(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideosAPIService UpdateVideo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var videoId string

		resp, httpRes, err := apiClient.VideosAPI.UpdateVideo(context.Background(), videoId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
