/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetDeviceFiles200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceFiles200Response{}

// GetDeviceFiles200Response A paginated list of files for a device.
type GetDeviceFiles200Response struct {
	Data []GetAppFiles200ResponseDataInner `json:"data,omitempty"`
	Links *GetDeviceFiles200ResponseLinks `json:"links,omitempty"`
	Meta *GetDeviceFiles200ResponseMeta `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetDeviceFiles200Response GetDeviceFiles200Response

// NewGetDeviceFiles200Response instantiates a new GetDeviceFiles200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceFiles200Response() *GetDeviceFiles200Response {
	this := GetDeviceFiles200Response{}
	return &this
}

// NewGetDeviceFiles200ResponseWithDefaults instantiates a new GetDeviceFiles200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceFiles200ResponseWithDefaults() *GetDeviceFiles200Response {
	this := GetDeviceFiles200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetDeviceFiles200Response) GetData() []GetAppFiles200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetAppFiles200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeviceFiles200Response) GetDataOk() ([]GetAppFiles200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetDeviceFiles200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetAppFiles200ResponseDataInner and assigns it to the Data field.
func (o *GetDeviceFiles200Response) SetData(v []GetAppFiles200ResponseDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetDeviceFiles200Response) GetLinks() GetDeviceFiles200ResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret GetDeviceFiles200ResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeviceFiles200Response) GetLinksOk() (*GetDeviceFiles200ResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetDeviceFiles200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given GetDeviceFiles200ResponseLinks and assigns it to the Links field.
func (o *GetDeviceFiles200Response) SetLinks(v GetDeviceFiles200ResponseLinks) {
	o.Links = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetDeviceFiles200Response) GetMeta() GetDeviceFiles200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret GetDeviceFiles200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeviceFiles200Response) GetMetaOk() (*GetDeviceFiles200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetDeviceFiles200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given GetDeviceFiles200ResponseMeta and assigns it to the Meta field.
func (o *GetDeviceFiles200Response) SetMeta(v GetDeviceFiles200ResponseMeta) {
	o.Meta = &v
}

func (o GetDeviceFiles200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceFiles200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDeviceFiles200Response) UnmarshalJSON(data []byte) (err error) {
	varGetDeviceFiles200Response := _GetDeviceFiles200Response{}

	err = json.Unmarshal(data, &varGetDeviceFiles200Response)

	if err != nil {
		return err
	}

	*o = GetDeviceFiles200Response(varGetDeviceFiles200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "links")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDeviceFiles200Response struct {
	value *GetDeviceFiles200Response
	isSet bool
}

func (v NullableGetDeviceFiles200Response) Get() *GetDeviceFiles200Response {
	return v.value
}

func (v *NullableGetDeviceFiles200Response) Set(val *GetDeviceFiles200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceFiles200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceFiles200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceFiles200Response(val *GetDeviceFiles200Response) *NullableGetDeviceFiles200Response {
	return &NullableGetDeviceFiles200Response{value: val, isSet: true}
}

func (v NullableGetDeviceFiles200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceFiles200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


