/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PreSignVideoUpload200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreSignVideoUpload200ResponseInner{}

// PreSignVideoUpload200ResponseInner struct for PreSignVideoUpload200ResponseInner
type PreSignVideoUpload200ResponseInner struct {
	PartNumber int32 `json:"partNumber"`
	PresignedUrl string `json:"presignedUrl"`
	AdditionalProperties map[string]interface{}
}

type _PreSignVideoUpload200ResponseInner PreSignVideoUpload200ResponseInner

// NewPreSignVideoUpload200ResponseInner instantiates a new PreSignVideoUpload200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreSignVideoUpload200ResponseInner(partNumber int32, presignedUrl string) *PreSignVideoUpload200ResponseInner {
	this := PreSignVideoUpload200ResponseInner{}
	this.PartNumber = partNumber
	this.PresignedUrl = presignedUrl
	return &this
}

// NewPreSignVideoUpload200ResponseInnerWithDefaults instantiates a new PreSignVideoUpload200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreSignVideoUpload200ResponseInnerWithDefaults() *PreSignVideoUpload200ResponseInner {
	this := PreSignVideoUpload200ResponseInner{}
	return &this
}

// GetPartNumber returns the PartNumber field value
func (o *PreSignVideoUpload200ResponseInner) GetPartNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value
// and a boolean to check if the value has been set.
func (o *PreSignVideoUpload200ResponseInner) GetPartNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartNumber, true
}

// SetPartNumber sets field value
func (o *PreSignVideoUpload200ResponseInner) SetPartNumber(v int32) {
	o.PartNumber = v
}

// GetPresignedUrl returns the PresignedUrl field value
func (o *PreSignVideoUpload200ResponseInner) GetPresignedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PresignedUrl
}

// GetPresignedUrlOk returns a tuple with the PresignedUrl field value
// and a boolean to check if the value has been set.
func (o *PreSignVideoUpload200ResponseInner) GetPresignedUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PresignedUrl, true
}

// SetPresignedUrl sets field value
func (o *PreSignVideoUpload200ResponseInner) SetPresignedUrl(v string) {
	o.PresignedUrl = v
}

func (o PreSignVideoUpload200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreSignVideoUpload200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["partNumber"] = o.PartNumber
	toSerialize["presignedUrl"] = o.PresignedUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PreSignVideoUpload200ResponseInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"partNumber",
		"presignedUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPreSignVideoUpload200ResponseInner := _PreSignVideoUpload200ResponseInner{}

	err = json.Unmarshal(data, &varPreSignVideoUpload200ResponseInner)

	if err != nil {
		return err
	}

	*o = PreSignVideoUpload200ResponseInner(varPreSignVideoUpload200ResponseInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "partNumber")
		delete(additionalProperties, "presignedUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePreSignVideoUpload200ResponseInner struct {
	value *PreSignVideoUpload200ResponseInner
	isSet bool
}

func (v NullablePreSignVideoUpload200ResponseInner) Get() *PreSignVideoUpload200ResponseInner {
	return v.value
}

func (v *NullablePreSignVideoUpload200ResponseInner) Set(val *PreSignVideoUpload200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePreSignVideoUpload200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePreSignVideoUpload200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreSignVideoUpload200ResponseInner(val *PreSignVideoUpload200ResponseInner) *NullablePreSignVideoUpload200ResponseInner {
	return &NullablePreSignVideoUpload200ResponseInner{value: val, isSet: true}
}

func (v NullablePreSignVideoUpload200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreSignVideoUpload200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


