/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AddFileToGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddFileToGroupRequest{}

// AddFileToGroupRequest struct for AddFileToGroupRequest
type AddFileToGroupRequest struct {
	// The ID of the file to add to the group
	FileId string `json:"fileId"`
	AdditionalProperties map[string]interface{}
}

type _AddFileToGroupRequest AddFileToGroupRequest

// NewAddFileToGroupRequest instantiates a new AddFileToGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddFileToGroupRequest(fileId string) *AddFileToGroupRequest {
	this := AddFileToGroupRequest{}
	this.FileId = fileId
	return &this
}

// NewAddFileToGroupRequestWithDefaults instantiates a new AddFileToGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddFileToGroupRequestWithDefaults() *AddFileToGroupRequest {
	this := AddFileToGroupRequest{}
	return &this
}

// GetFileId returns the FileId field value
func (o *AddFileToGroupRequest) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *AddFileToGroupRequest) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *AddFileToGroupRequest) SetFileId(v string) {
	o.FileId = v
}

func (o AddFileToGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddFileToGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fileId"] = o.FileId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddFileToGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fileId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddFileToGroupRequest := _AddFileToGroupRequest{}

	err = json.Unmarshal(data, &varAddFileToGroupRequest)

	if err != nil {
		return err
	}

	*o = AddFileToGroupRequest(varAddFileToGroupRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fileId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddFileToGroupRequest struct {
	value *AddFileToGroupRequest
	isSet bool
}

func (v NullableAddFileToGroupRequest) Get() *AddFileToGroupRequest {
	return v.value
}

func (v *NullableAddFileToGroupRequest) Set(val *AddFileToGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddFileToGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddFileToGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddFileToGroupRequest(val *AddFileToGroupRequest) *NullableAddFileToGroupRequest {
	return &NullableAddFileToGroupRequest{value: val, isSet: true}
}

func (v NullableAddFileToGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddFileToGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


