/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateUserRequestGroupRolesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserRequestGroupRolesInner{}

// CreateUserRequestGroupRolesInner struct for CreateUserRequestGroupRolesInner
type CreateUserRequestGroupRolesInner struct {
	RoleId string `json:"roleId"`
	GroupId string `json:"groupId"`
	AdditionalProperties map[string]interface{}
}

type _CreateUserRequestGroupRolesInner CreateUserRequestGroupRolesInner

// NewCreateUserRequestGroupRolesInner instantiates a new CreateUserRequestGroupRolesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserRequestGroupRolesInner(roleId string, groupId string) *CreateUserRequestGroupRolesInner {
	this := CreateUserRequestGroupRolesInner{}
	this.RoleId = roleId
	this.GroupId = groupId
	return &this
}

// NewCreateUserRequestGroupRolesInnerWithDefaults instantiates a new CreateUserRequestGroupRolesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserRequestGroupRolesInnerWithDefaults() *CreateUserRequestGroupRolesInner {
	this := CreateUserRequestGroupRolesInner{}
	return &this
}

// GetRoleId returns the RoleId field value
func (o *CreateUserRequestGroupRolesInner) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *CreateUserRequestGroupRolesInner) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *CreateUserRequestGroupRolesInner) SetRoleId(v string) {
	o.RoleId = v
}

// GetGroupId returns the GroupId field value
func (o *CreateUserRequestGroupRolesInner) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *CreateUserRequestGroupRolesInner) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *CreateUserRequestGroupRolesInner) SetGroupId(v string) {
	o.GroupId = v
}

func (o CreateUserRequestGroupRolesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserRequestGroupRolesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roleId"] = o.RoleId
	toSerialize["groupId"] = o.GroupId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateUserRequestGroupRolesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roleId",
		"groupId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUserRequestGroupRolesInner := _CreateUserRequestGroupRolesInner{}

	err = json.Unmarshal(data, &varCreateUserRequestGroupRolesInner)

	if err != nil {
		return err
	}

	*o = CreateUserRequestGroupRolesInner(varCreateUserRequestGroupRolesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "roleId")
		delete(additionalProperties, "groupId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateUserRequestGroupRolesInner struct {
	value *CreateUserRequestGroupRolesInner
	isSet bool
}

func (v NullableCreateUserRequestGroupRolesInner) Get() *CreateUserRequestGroupRolesInner {
	return v.value
}

func (v *NullableCreateUserRequestGroupRolesInner) Set(val *CreateUserRequestGroupRolesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserRequestGroupRolesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserRequestGroupRolesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserRequestGroupRolesInner(val *CreateUserRequestGroupRolesInner) *NullableCreateUserRequestGroupRolesInner {
	return &NullableCreateUserRequestGroupRolesInner{value: val, isSet: true}
}

func (v NullableCreateUserRequestGroupRolesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserRequestGroupRolesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


