/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetVideos200ResponseDataInnerDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVideos200ResponseDataInnerDetails{}

// GetVideos200ResponseDataInnerDetails struct for GetVideos200ResponseDataInnerDetails
type GetVideos200ResponseDataInnerDetails struct {
	VideoType *string `json:"videoType,omitempty"`
	VideoMapping NullableString `json:"videoMapping,omitempty"`
	VideoDisplay NullableString `json:"videoDisplay,omitempty"`
	VideoPacking NullableString `json:"videoPacking,omitempty"`
	AudioEncoding *string `json:"audioEncoding,omitempty"`
	PlaytimeSeconds NullableFloat32 `json:"playtimeSeconds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetVideos200ResponseDataInnerDetails GetVideos200ResponseDataInnerDetails

// NewGetVideos200ResponseDataInnerDetails instantiates a new GetVideos200ResponseDataInnerDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVideos200ResponseDataInnerDetails() *GetVideos200ResponseDataInnerDetails {
	this := GetVideos200ResponseDataInnerDetails{}
	return &this
}

// NewGetVideos200ResponseDataInnerDetailsWithDefaults instantiates a new GetVideos200ResponseDataInnerDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVideos200ResponseDataInnerDetailsWithDefaults() *GetVideos200ResponseDataInnerDetails {
	this := GetVideos200ResponseDataInnerDetails{}
	return &this
}

// GetVideoType returns the VideoType field value if set, zero value otherwise.
func (o *GetVideos200ResponseDataInnerDetails) GetVideoType() string {
	if o == nil || IsNil(o.VideoType) {
		var ret string
		return ret
	}
	return *o.VideoType
}

// GetVideoTypeOk returns a tuple with the VideoType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseDataInnerDetails) GetVideoTypeOk() (*string, bool) {
	if o == nil || IsNil(o.VideoType) {
		return nil, false
	}
	return o.VideoType, true
}

// HasVideoType returns a boolean if a field has been set.
func (o *GetVideos200ResponseDataInnerDetails) HasVideoType() bool {
	if o != nil && !IsNil(o.VideoType) {
		return true
	}

	return false
}

// SetVideoType gets a reference to the given string and assigns it to the VideoType field.
func (o *GetVideos200ResponseDataInnerDetails) SetVideoType(v string) {
	o.VideoType = &v
}

// GetVideoMapping returns the VideoMapping field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideos200ResponseDataInnerDetails) GetVideoMapping() string {
	if o == nil || IsNil(o.VideoMapping.Get()) {
		var ret string
		return ret
	}
	return *o.VideoMapping.Get()
}

// GetVideoMappingOk returns a tuple with the VideoMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideos200ResponseDataInnerDetails) GetVideoMappingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoMapping.Get(), o.VideoMapping.IsSet()
}

// HasVideoMapping returns a boolean if a field has been set.
func (o *GetVideos200ResponseDataInnerDetails) HasVideoMapping() bool {
	if o != nil && o.VideoMapping.IsSet() {
		return true
	}

	return false
}

// SetVideoMapping gets a reference to the given NullableString and assigns it to the VideoMapping field.
func (o *GetVideos200ResponseDataInnerDetails) SetVideoMapping(v string) {
	o.VideoMapping.Set(&v)
}
// SetVideoMappingNil sets the value for VideoMapping to be an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) SetVideoMappingNil() {
	o.VideoMapping.Set(nil)
}

// UnsetVideoMapping ensures that no value is present for VideoMapping, not even an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) UnsetVideoMapping() {
	o.VideoMapping.Unset()
}

// GetVideoDisplay returns the VideoDisplay field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideos200ResponseDataInnerDetails) GetVideoDisplay() string {
	if o == nil || IsNil(o.VideoDisplay.Get()) {
		var ret string
		return ret
	}
	return *o.VideoDisplay.Get()
}

// GetVideoDisplayOk returns a tuple with the VideoDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideos200ResponseDataInnerDetails) GetVideoDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoDisplay.Get(), o.VideoDisplay.IsSet()
}

// HasVideoDisplay returns a boolean if a field has been set.
func (o *GetVideos200ResponseDataInnerDetails) HasVideoDisplay() bool {
	if o != nil && o.VideoDisplay.IsSet() {
		return true
	}

	return false
}

// SetVideoDisplay gets a reference to the given NullableString and assigns it to the VideoDisplay field.
func (o *GetVideos200ResponseDataInnerDetails) SetVideoDisplay(v string) {
	o.VideoDisplay.Set(&v)
}
// SetVideoDisplayNil sets the value for VideoDisplay to be an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) SetVideoDisplayNil() {
	o.VideoDisplay.Set(nil)
}

// UnsetVideoDisplay ensures that no value is present for VideoDisplay, not even an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) UnsetVideoDisplay() {
	o.VideoDisplay.Unset()
}

// GetVideoPacking returns the VideoPacking field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideos200ResponseDataInnerDetails) GetVideoPacking() string {
	if o == nil || IsNil(o.VideoPacking.Get()) {
		var ret string
		return ret
	}
	return *o.VideoPacking.Get()
}

// GetVideoPackingOk returns a tuple with the VideoPacking field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideos200ResponseDataInnerDetails) GetVideoPackingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoPacking.Get(), o.VideoPacking.IsSet()
}

// HasVideoPacking returns a boolean if a field has been set.
func (o *GetVideos200ResponseDataInnerDetails) HasVideoPacking() bool {
	if o != nil && o.VideoPacking.IsSet() {
		return true
	}

	return false
}

// SetVideoPacking gets a reference to the given NullableString and assigns it to the VideoPacking field.
func (o *GetVideos200ResponseDataInnerDetails) SetVideoPacking(v string) {
	o.VideoPacking.Set(&v)
}
// SetVideoPackingNil sets the value for VideoPacking to be an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) SetVideoPackingNil() {
	o.VideoPacking.Set(nil)
}

// UnsetVideoPacking ensures that no value is present for VideoPacking, not even an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) UnsetVideoPacking() {
	o.VideoPacking.Unset()
}

// GetAudioEncoding returns the AudioEncoding field value if set, zero value otherwise.
func (o *GetVideos200ResponseDataInnerDetails) GetAudioEncoding() string {
	if o == nil || IsNil(o.AudioEncoding) {
		var ret string
		return ret
	}
	return *o.AudioEncoding
}

// GetAudioEncodingOk returns a tuple with the AudioEncoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseDataInnerDetails) GetAudioEncodingOk() (*string, bool) {
	if o == nil || IsNil(o.AudioEncoding) {
		return nil, false
	}
	return o.AudioEncoding, true
}

// HasAudioEncoding returns a boolean if a field has been set.
func (o *GetVideos200ResponseDataInnerDetails) HasAudioEncoding() bool {
	if o != nil && !IsNil(o.AudioEncoding) {
		return true
	}

	return false
}

// SetAudioEncoding gets a reference to the given string and assigns it to the AudioEncoding field.
func (o *GetVideos200ResponseDataInnerDetails) SetAudioEncoding(v string) {
	o.AudioEncoding = &v
}

// GetPlaytimeSeconds returns the PlaytimeSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideos200ResponseDataInnerDetails) GetPlaytimeSeconds() float32 {
	if o == nil || IsNil(o.PlaytimeSeconds.Get()) {
		var ret float32
		return ret
	}
	return *o.PlaytimeSeconds.Get()
}

// GetPlaytimeSecondsOk returns a tuple with the PlaytimeSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideos200ResponseDataInnerDetails) GetPlaytimeSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlaytimeSeconds.Get(), o.PlaytimeSeconds.IsSet()
}

// HasPlaytimeSeconds returns a boolean if a field has been set.
func (o *GetVideos200ResponseDataInnerDetails) HasPlaytimeSeconds() bool {
	if o != nil && o.PlaytimeSeconds.IsSet() {
		return true
	}

	return false
}

// SetPlaytimeSeconds gets a reference to the given NullableFloat32 and assigns it to the PlaytimeSeconds field.
func (o *GetVideos200ResponseDataInnerDetails) SetPlaytimeSeconds(v float32) {
	o.PlaytimeSeconds.Set(&v)
}
// SetPlaytimeSecondsNil sets the value for PlaytimeSeconds to be an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) SetPlaytimeSecondsNil() {
	o.PlaytimeSeconds.Set(nil)
}

// UnsetPlaytimeSeconds ensures that no value is present for PlaytimeSeconds, not even an explicit nil
func (o *GetVideos200ResponseDataInnerDetails) UnsetPlaytimeSeconds() {
	o.PlaytimeSeconds.Unset()
}

func (o GetVideos200ResponseDataInnerDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVideos200ResponseDataInnerDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VideoType) {
		toSerialize["videoType"] = o.VideoType
	}
	if o.VideoMapping.IsSet() {
		toSerialize["videoMapping"] = o.VideoMapping.Get()
	}
	if o.VideoDisplay.IsSet() {
		toSerialize["videoDisplay"] = o.VideoDisplay.Get()
	}
	if o.VideoPacking.IsSet() {
		toSerialize["videoPacking"] = o.VideoPacking.Get()
	}
	if !IsNil(o.AudioEncoding) {
		toSerialize["audioEncoding"] = o.AudioEncoding
	}
	if o.PlaytimeSeconds.IsSet() {
		toSerialize["playtimeSeconds"] = o.PlaytimeSeconds.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetVideos200ResponseDataInnerDetails) UnmarshalJSON(data []byte) (err error) {
	varGetVideos200ResponseDataInnerDetails := _GetVideos200ResponseDataInnerDetails{}

	err = json.Unmarshal(data, &varGetVideos200ResponseDataInnerDetails)

	if err != nil {
		return err
	}

	*o = GetVideos200ResponseDataInnerDetails(varGetVideos200ResponseDataInnerDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "videoType")
		delete(additionalProperties, "videoMapping")
		delete(additionalProperties, "videoDisplay")
		delete(additionalProperties, "videoPacking")
		delete(additionalProperties, "audioEncoding")
		delete(additionalProperties, "playtimeSeconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetVideos200ResponseDataInnerDetails struct {
	value *GetVideos200ResponseDataInnerDetails
	isSet bool
}

func (v NullableGetVideos200ResponseDataInnerDetails) Get() *GetVideos200ResponseDataInnerDetails {
	return v.value
}

func (v *NullableGetVideos200ResponseDataInnerDetails) Set(val *GetVideos200ResponseDataInnerDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVideos200ResponseDataInnerDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVideos200ResponseDataInnerDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVideos200ResponseDataInnerDetails(val *GetVideos200ResponseDataInnerDetails) *NullableGetVideos200ResponseDataInnerDetails {
	return &NullableGetVideos200ResponseDataInnerDetails{value: val, isSet: true}
}

func (v NullableGetVideos200ResponseDataInnerDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVideos200ResponseDataInnerDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


