/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the InitiateCustom3DEnvironmentUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiateCustom3DEnvironmentUploadRequest{}

// InitiateCustom3DEnvironmentUploadRequest struct for InitiateCustom3DEnvironmentUploadRequest
type InitiateCustom3DEnvironmentUploadRequest struct {
	// The filename for the 3D environment (must have .glb extension)
	Filename string `json:"filename"`
	AdditionalProperties map[string]interface{}
}

type _InitiateCustom3DEnvironmentUploadRequest InitiateCustom3DEnvironmentUploadRequest

// NewInitiateCustom3DEnvironmentUploadRequest instantiates a new InitiateCustom3DEnvironmentUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiateCustom3DEnvironmentUploadRequest(filename string) *InitiateCustom3DEnvironmentUploadRequest {
	this := InitiateCustom3DEnvironmentUploadRequest{}
	this.Filename = filename
	return &this
}

// NewInitiateCustom3DEnvironmentUploadRequestWithDefaults instantiates a new InitiateCustom3DEnvironmentUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiateCustom3DEnvironmentUploadRequestWithDefaults() *InitiateCustom3DEnvironmentUploadRequest {
	this := InitiateCustom3DEnvironmentUploadRequest{}
	return &this
}

// GetFilename returns the Filename field value
func (o *InitiateCustom3DEnvironmentUploadRequest) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *InitiateCustom3DEnvironmentUploadRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *InitiateCustom3DEnvironmentUploadRequest) SetFilename(v string) {
	o.Filename = v
}

func (o InitiateCustom3DEnvironmentUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiateCustom3DEnvironmentUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filename"] = o.Filename

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InitiateCustom3DEnvironmentUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filename",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiateCustom3DEnvironmentUploadRequest := _InitiateCustom3DEnvironmentUploadRequest{}

	err = json.Unmarshal(data, &varInitiateCustom3DEnvironmentUploadRequest)

	if err != nil {
		return err
	}

	*o = InitiateCustom3DEnvironmentUploadRequest(varInitiateCustom3DEnvironmentUploadRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filename")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInitiateCustom3DEnvironmentUploadRequest struct {
	value *InitiateCustom3DEnvironmentUploadRequest
	isSet bool
}

func (v NullableInitiateCustom3DEnvironmentUploadRequest) Get() *InitiateCustom3DEnvironmentUploadRequest {
	return v.value
}

func (v *NullableInitiateCustom3DEnvironmentUploadRequest) Set(val *InitiateCustom3DEnvironmentUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateCustom3DEnvironmentUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateCustom3DEnvironmentUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateCustom3DEnvironmentUploadRequest(val *InitiateCustom3DEnvironmentUploadRequest) *NullableInitiateCustom3DEnvironmentUploadRequest {
	return &NullableInitiateCustom3DEnvironmentUploadRequest{value: val, isSet: true}
}

func (v NullableInitiateCustom3DEnvironmentUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateCustom3DEnvironmentUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


