/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the QueryInsightsData200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryInsightsData200Response{}

// QueryInsightsData200Response A paginated list of insights analytics data. The shape of items in the data array varies by collection type.
type QueryInsightsData200Response struct {
	// Array of analytics data items. The schema of each item varies depending on the collection type and query parameters.
	Data []map[string]interface{} `json:"data,omitempty"`
	// The next page number, or null if there are no more pages.
	NextPage NullableInt32 `json:"next_page,omitempty"`
	// The previous page number, or null if on the first page.
	PrevPage NullableInt32 `json:"prev_page,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _QueryInsightsData200Response QueryInsightsData200Response

// NewQueryInsightsData200Response instantiates a new QueryInsightsData200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryInsightsData200Response() *QueryInsightsData200Response {
	this := QueryInsightsData200Response{}
	return &this
}

// NewQueryInsightsData200ResponseWithDefaults instantiates a new QueryInsightsData200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryInsightsData200ResponseWithDefaults() *QueryInsightsData200Response {
	this := QueryInsightsData200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *QueryInsightsData200Response) GetData() []map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryInsightsData200Response) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *QueryInsightsData200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []map[string]interface{} and assigns it to the Data field.
func (o *QueryInsightsData200Response) SetData(v []map[string]interface{}) {
	o.Data = v
}

// GetNextPage returns the NextPage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryInsightsData200Response) GetNextPage() int32 {
	if o == nil || IsNil(o.NextPage.Get()) {
		var ret int32
		return ret
	}
	return *o.NextPage.Get()
}

// GetNextPageOk returns a tuple with the NextPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryInsightsData200Response) GetNextPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPage.Get(), o.NextPage.IsSet()
}

// HasNextPage returns a boolean if a field has been set.
func (o *QueryInsightsData200Response) HasNextPage() bool {
	if o != nil && o.NextPage.IsSet() {
		return true
	}

	return false
}

// SetNextPage gets a reference to the given NullableInt32 and assigns it to the NextPage field.
func (o *QueryInsightsData200Response) SetNextPage(v int32) {
	o.NextPage.Set(&v)
}
// SetNextPageNil sets the value for NextPage to be an explicit nil
func (o *QueryInsightsData200Response) SetNextPageNil() {
	o.NextPage.Set(nil)
}

// UnsetNextPage ensures that no value is present for NextPage, not even an explicit nil
func (o *QueryInsightsData200Response) UnsetNextPage() {
	o.NextPage.Unset()
}

// GetPrevPage returns the PrevPage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryInsightsData200Response) GetPrevPage() int32 {
	if o == nil || IsNil(o.PrevPage.Get()) {
		var ret int32
		return ret
	}
	return *o.PrevPage.Get()
}

// GetPrevPageOk returns a tuple with the PrevPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryInsightsData200Response) GetPrevPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrevPage.Get(), o.PrevPage.IsSet()
}

// HasPrevPage returns a boolean if a field has been set.
func (o *QueryInsightsData200Response) HasPrevPage() bool {
	if o != nil && o.PrevPage.IsSet() {
		return true
	}

	return false
}

// SetPrevPage gets a reference to the given NullableInt32 and assigns it to the PrevPage field.
func (o *QueryInsightsData200Response) SetPrevPage(v int32) {
	o.PrevPage.Set(&v)
}
// SetPrevPageNil sets the value for PrevPage to be an explicit nil
func (o *QueryInsightsData200Response) SetPrevPageNil() {
	o.PrevPage.Set(nil)
}

// UnsetPrevPage ensures that no value is present for PrevPage, not even an explicit nil
func (o *QueryInsightsData200Response) UnsetPrevPage() {
	o.PrevPage.Unset()
}

func (o QueryInsightsData200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryInsightsData200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.NextPage.IsSet() {
		toSerialize["next_page"] = o.NextPage.Get()
	}
	if o.PrevPage.IsSet() {
		toSerialize["prev_page"] = o.PrevPage.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QueryInsightsData200Response) UnmarshalJSON(data []byte) (err error) {
	varQueryInsightsData200Response := _QueryInsightsData200Response{}

	err = json.Unmarshal(data, &varQueryInsightsData200Response)

	if err != nil {
		return err
	}

	*o = QueryInsightsData200Response(varQueryInsightsData200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "next_page")
		delete(additionalProperties, "prev_page")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQueryInsightsData200Response struct {
	value *QueryInsightsData200Response
	isSet bool
}

func (v NullableQueryInsightsData200Response) Get() *QueryInsightsData200Response {
	return v.value
}

func (v *NullableQueryInsightsData200Response) Set(val *QueryInsightsData200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryInsightsData200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryInsightsData200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryInsightsData200Response(val *QueryInsightsData200Response) *NullableQueryInsightsData200Response {
	return &NullableQueryInsightsData200Response{value: val, isSet: true}
}

func (v NullableQueryInsightsData200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryInsightsData200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


