/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetStatuses200ResponseDataInnerContent - struct for GetStatuses200ResponseDataInnerContent
type GetStatuses200ResponseDataInnerContent struct {
	GetStatuses200ResponseDataInnerContentOneOf *GetStatuses200ResponseDataInnerContentOneOf
	GetStatuses200ResponseDataInnerContentOneOf1 *GetStatuses200ResponseDataInnerContentOneOf1
	GetStatuses200ResponseDataInnerContentOneOf2 *GetStatuses200ResponseDataInnerContentOneOf2
	GetStatuses200ResponseDataInnerContentOneOf3 *GetStatuses200ResponseDataInnerContentOneOf3
	GetStatuses200ResponseDataInnerContentOneOf4 *GetStatuses200ResponseDataInnerContentOneOf4
	GetStatuses200ResponseDataInnerContentOneOf5 *GetStatuses200ResponseDataInnerContentOneOf5
	GetStatuses200ResponseDataInnerContentOneOf6 *GetStatuses200ResponseDataInnerContentOneOf6
}

// GetStatuses200ResponseDataInnerContentOneOfAsGetStatuses200ResponseDataInnerContent is a convenience function that returns GetStatuses200ResponseDataInnerContentOneOf wrapped in GetStatuses200ResponseDataInnerContent
func GetStatuses200ResponseDataInnerContentOneOfAsGetStatuses200ResponseDataInnerContent(v *GetStatuses200ResponseDataInnerContentOneOf) GetStatuses200ResponseDataInnerContent {
	return GetStatuses200ResponseDataInnerContent{
		GetStatuses200ResponseDataInnerContentOneOf: v,
	}
}

// GetStatuses200ResponseDataInnerContentOneOf1AsGetStatuses200ResponseDataInnerContent is a convenience function that returns GetStatuses200ResponseDataInnerContentOneOf1 wrapped in GetStatuses200ResponseDataInnerContent
func GetStatuses200ResponseDataInnerContentOneOf1AsGetStatuses200ResponseDataInnerContent(v *GetStatuses200ResponseDataInnerContentOneOf1) GetStatuses200ResponseDataInnerContent {
	return GetStatuses200ResponseDataInnerContent{
		GetStatuses200ResponseDataInnerContentOneOf1: v,
	}
}

// GetStatuses200ResponseDataInnerContentOneOf2AsGetStatuses200ResponseDataInnerContent is a convenience function that returns GetStatuses200ResponseDataInnerContentOneOf2 wrapped in GetStatuses200ResponseDataInnerContent
func GetStatuses200ResponseDataInnerContentOneOf2AsGetStatuses200ResponseDataInnerContent(v *GetStatuses200ResponseDataInnerContentOneOf2) GetStatuses200ResponseDataInnerContent {
	return GetStatuses200ResponseDataInnerContent{
		GetStatuses200ResponseDataInnerContentOneOf2: v,
	}
}

// GetStatuses200ResponseDataInnerContentOneOf3AsGetStatuses200ResponseDataInnerContent is a convenience function that returns GetStatuses200ResponseDataInnerContentOneOf3 wrapped in GetStatuses200ResponseDataInnerContent
func GetStatuses200ResponseDataInnerContentOneOf3AsGetStatuses200ResponseDataInnerContent(v *GetStatuses200ResponseDataInnerContentOneOf3) GetStatuses200ResponseDataInnerContent {
	return GetStatuses200ResponseDataInnerContent{
		GetStatuses200ResponseDataInnerContentOneOf3: v,
	}
}

// GetStatuses200ResponseDataInnerContentOneOf4AsGetStatuses200ResponseDataInnerContent is a convenience function that returns GetStatuses200ResponseDataInnerContentOneOf4 wrapped in GetStatuses200ResponseDataInnerContent
func GetStatuses200ResponseDataInnerContentOneOf4AsGetStatuses200ResponseDataInnerContent(v *GetStatuses200ResponseDataInnerContentOneOf4) GetStatuses200ResponseDataInnerContent {
	return GetStatuses200ResponseDataInnerContent{
		GetStatuses200ResponseDataInnerContentOneOf4: v,
	}
}

// GetStatuses200ResponseDataInnerContentOneOf5AsGetStatuses200ResponseDataInnerContent is a convenience function that returns GetStatuses200ResponseDataInnerContentOneOf5 wrapped in GetStatuses200ResponseDataInnerContent
func GetStatuses200ResponseDataInnerContentOneOf5AsGetStatuses200ResponseDataInnerContent(v *GetStatuses200ResponseDataInnerContentOneOf5) GetStatuses200ResponseDataInnerContent {
	return GetStatuses200ResponseDataInnerContent{
		GetStatuses200ResponseDataInnerContentOneOf5: v,
	}
}

// GetStatuses200ResponseDataInnerContentOneOf6AsGetStatuses200ResponseDataInnerContent is a convenience function that returns GetStatuses200ResponseDataInnerContentOneOf6 wrapped in GetStatuses200ResponseDataInnerContent
func GetStatuses200ResponseDataInnerContentOneOf6AsGetStatuses200ResponseDataInnerContent(v *GetStatuses200ResponseDataInnerContentOneOf6) GetStatuses200ResponseDataInnerContent {
	return GetStatuses200ResponseDataInnerContent{
		GetStatuses200ResponseDataInnerContentOneOf6: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetStatuses200ResponseDataInnerContent) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GetStatuses200ResponseDataInnerContentOneOf
	err = newStrictDecoder(data).Decode(&dst.GetStatuses200ResponseDataInnerContentOneOf)
	if err == nil {
		jsonGetStatuses200ResponseDataInnerContentOneOf, _ := json.Marshal(dst.GetStatuses200ResponseDataInnerContentOneOf)
		if string(jsonGetStatuses200ResponseDataInnerContentOneOf) == "{}" { // empty struct
			dst.GetStatuses200ResponseDataInnerContentOneOf = nil
		} else {
			if err = validator.Validate(dst.GetStatuses200ResponseDataInnerContentOneOf); err != nil {
				dst.GetStatuses200ResponseDataInnerContentOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetStatuses200ResponseDataInnerContentOneOf = nil
	}

	// try to unmarshal data into GetStatuses200ResponseDataInnerContentOneOf1
	err = newStrictDecoder(data).Decode(&dst.GetStatuses200ResponseDataInnerContentOneOf1)
	if err == nil {
		jsonGetStatuses200ResponseDataInnerContentOneOf1, _ := json.Marshal(dst.GetStatuses200ResponseDataInnerContentOneOf1)
		if string(jsonGetStatuses200ResponseDataInnerContentOneOf1) == "{}" { // empty struct
			dst.GetStatuses200ResponseDataInnerContentOneOf1 = nil
		} else {
			if err = validator.Validate(dst.GetStatuses200ResponseDataInnerContentOneOf1); err != nil {
				dst.GetStatuses200ResponseDataInnerContentOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetStatuses200ResponseDataInnerContentOneOf1 = nil
	}

	// try to unmarshal data into GetStatuses200ResponseDataInnerContentOneOf2
	err = newStrictDecoder(data).Decode(&dst.GetStatuses200ResponseDataInnerContentOneOf2)
	if err == nil {
		jsonGetStatuses200ResponseDataInnerContentOneOf2, _ := json.Marshal(dst.GetStatuses200ResponseDataInnerContentOneOf2)
		if string(jsonGetStatuses200ResponseDataInnerContentOneOf2) == "{}" { // empty struct
			dst.GetStatuses200ResponseDataInnerContentOneOf2 = nil
		} else {
			if err = validator.Validate(dst.GetStatuses200ResponseDataInnerContentOneOf2); err != nil {
				dst.GetStatuses200ResponseDataInnerContentOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetStatuses200ResponseDataInnerContentOneOf2 = nil
	}

	// try to unmarshal data into GetStatuses200ResponseDataInnerContentOneOf3
	err = newStrictDecoder(data).Decode(&dst.GetStatuses200ResponseDataInnerContentOneOf3)
	if err == nil {
		jsonGetStatuses200ResponseDataInnerContentOneOf3, _ := json.Marshal(dst.GetStatuses200ResponseDataInnerContentOneOf3)
		if string(jsonGetStatuses200ResponseDataInnerContentOneOf3) == "{}" { // empty struct
			dst.GetStatuses200ResponseDataInnerContentOneOf3 = nil
		} else {
			if err = validator.Validate(dst.GetStatuses200ResponseDataInnerContentOneOf3); err != nil {
				dst.GetStatuses200ResponseDataInnerContentOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetStatuses200ResponseDataInnerContentOneOf3 = nil
	}

	// try to unmarshal data into GetStatuses200ResponseDataInnerContentOneOf4
	err = newStrictDecoder(data).Decode(&dst.GetStatuses200ResponseDataInnerContentOneOf4)
	if err == nil {
		jsonGetStatuses200ResponseDataInnerContentOneOf4, _ := json.Marshal(dst.GetStatuses200ResponseDataInnerContentOneOf4)
		if string(jsonGetStatuses200ResponseDataInnerContentOneOf4) == "{}" { // empty struct
			dst.GetStatuses200ResponseDataInnerContentOneOf4 = nil
		} else {
			if err = validator.Validate(dst.GetStatuses200ResponseDataInnerContentOneOf4); err != nil {
				dst.GetStatuses200ResponseDataInnerContentOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetStatuses200ResponseDataInnerContentOneOf4 = nil
	}

	// try to unmarshal data into GetStatuses200ResponseDataInnerContentOneOf5
	err = newStrictDecoder(data).Decode(&dst.GetStatuses200ResponseDataInnerContentOneOf5)
	if err == nil {
		jsonGetStatuses200ResponseDataInnerContentOneOf5, _ := json.Marshal(dst.GetStatuses200ResponseDataInnerContentOneOf5)
		if string(jsonGetStatuses200ResponseDataInnerContentOneOf5) == "{}" { // empty struct
			dst.GetStatuses200ResponseDataInnerContentOneOf5 = nil
		} else {
			if err = validator.Validate(dst.GetStatuses200ResponseDataInnerContentOneOf5); err != nil {
				dst.GetStatuses200ResponseDataInnerContentOneOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetStatuses200ResponseDataInnerContentOneOf5 = nil
	}

	// try to unmarshal data into GetStatuses200ResponseDataInnerContentOneOf6
	err = newStrictDecoder(data).Decode(&dst.GetStatuses200ResponseDataInnerContentOneOf6)
	if err == nil {
		jsonGetStatuses200ResponseDataInnerContentOneOf6, _ := json.Marshal(dst.GetStatuses200ResponseDataInnerContentOneOf6)
		if string(jsonGetStatuses200ResponseDataInnerContentOneOf6) == "{}" { // empty struct
			dst.GetStatuses200ResponseDataInnerContentOneOf6 = nil
		} else {
			if err = validator.Validate(dst.GetStatuses200ResponseDataInnerContentOneOf6); err != nil {
				dst.GetStatuses200ResponseDataInnerContentOneOf6 = nil
			} else {
				match++
			}
		}
	} else {
		dst.GetStatuses200ResponseDataInnerContentOneOf6 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GetStatuses200ResponseDataInnerContentOneOf = nil
		dst.GetStatuses200ResponseDataInnerContentOneOf1 = nil
		dst.GetStatuses200ResponseDataInnerContentOneOf2 = nil
		dst.GetStatuses200ResponseDataInnerContentOneOf3 = nil
		dst.GetStatuses200ResponseDataInnerContentOneOf4 = nil
		dst.GetStatuses200ResponseDataInnerContentOneOf5 = nil
		dst.GetStatuses200ResponseDataInnerContentOneOf6 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetStatuses200ResponseDataInnerContent)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetStatuses200ResponseDataInnerContent)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetStatuses200ResponseDataInnerContent) MarshalJSON() ([]byte, error) {
	if src.GetStatuses200ResponseDataInnerContentOneOf != nil {
		return json.Marshal(&src.GetStatuses200ResponseDataInnerContentOneOf)
	}

	if src.GetStatuses200ResponseDataInnerContentOneOf1 != nil {
		return json.Marshal(&src.GetStatuses200ResponseDataInnerContentOneOf1)
	}

	if src.GetStatuses200ResponseDataInnerContentOneOf2 != nil {
		return json.Marshal(&src.GetStatuses200ResponseDataInnerContentOneOf2)
	}

	if src.GetStatuses200ResponseDataInnerContentOneOf3 != nil {
		return json.Marshal(&src.GetStatuses200ResponseDataInnerContentOneOf3)
	}

	if src.GetStatuses200ResponseDataInnerContentOneOf4 != nil {
		return json.Marshal(&src.GetStatuses200ResponseDataInnerContentOneOf4)
	}

	if src.GetStatuses200ResponseDataInnerContentOneOf5 != nil {
		return json.Marshal(&src.GetStatuses200ResponseDataInnerContentOneOf5)
	}

	if src.GetStatuses200ResponseDataInnerContentOneOf6 != nil {
		return json.Marshal(&src.GetStatuses200ResponseDataInnerContentOneOf6)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetStatuses200ResponseDataInnerContent) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.GetStatuses200ResponseDataInnerContentOneOf != nil {
		return obj.GetStatuses200ResponseDataInnerContentOneOf
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf1 != nil {
		return obj.GetStatuses200ResponseDataInnerContentOneOf1
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf2 != nil {
		return obj.GetStatuses200ResponseDataInnerContentOneOf2
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf3 != nil {
		return obj.GetStatuses200ResponseDataInnerContentOneOf3
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf4 != nil {
		return obj.GetStatuses200ResponseDataInnerContentOneOf4
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf5 != nil {
		return obj.GetStatuses200ResponseDataInnerContentOneOf5
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf6 != nil {
		return obj.GetStatuses200ResponseDataInnerContentOneOf6
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetStatuses200ResponseDataInnerContent) GetActualInstanceValue() (interface{}) {
	if obj.GetStatuses200ResponseDataInnerContentOneOf != nil {
		return *obj.GetStatuses200ResponseDataInnerContentOneOf
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf1 != nil {
		return *obj.GetStatuses200ResponseDataInnerContentOneOf1
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf2 != nil {
		return *obj.GetStatuses200ResponseDataInnerContentOneOf2
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf3 != nil {
		return *obj.GetStatuses200ResponseDataInnerContentOneOf3
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf4 != nil {
		return *obj.GetStatuses200ResponseDataInnerContentOneOf4
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf5 != nil {
		return *obj.GetStatuses200ResponseDataInnerContentOneOf5
	}

	if obj.GetStatuses200ResponseDataInnerContentOneOf6 != nil {
		return *obj.GetStatuses200ResponseDataInnerContentOneOf6
	}

	// all schemas are nil
	return nil
}

type NullableGetStatuses200ResponseDataInnerContent struct {
	value *GetStatuses200ResponseDataInnerContent
	isSet bool
}

func (v NullableGetStatuses200ResponseDataInnerContent) Get() *GetStatuses200ResponseDataInnerContent {
	return v.value
}

func (v *NullableGetStatuses200ResponseDataInnerContent) Set(val *GetStatuses200ResponseDataInnerContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatuses200ResponseDataInnerContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatuses200ResponseDataInnerContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatuses200ResponseDataInnerContent(val *GetStatuses200ResponseDataInnerContent) *NullableGetStatuses200ResponseDataInnerContent {
	return &NullableGetStatuses200ResponseDataInnerContent{value: val, isSet: true}
}

func (v NullableGetStatuses200ResponseDataInnerContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatuses200ResponseDataInnerContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


