/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetAppFiles200ResponseDataInnerDeviceStatusesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppFiles200ResponseDataInnerDeviceStatusesInner{}

// GetAppFiles200ResponseDataInnerDeviceStatusesInner struct for GetAppFiles200ResponseDataInnerDeviceStatusesInner
type GetAppFiles200ResponseDataInnerDeviceStatusesInner struct {
	DeviceId *string `json:"deviceId,omitempty"`
	Status *string `json:"status,omitempty"`
	StatusTimestamp *Time `json:"statusTimestamp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAppFiles200ResponseDataInnerDeviceStatusesInner GetAppFiles200ResponseDataInnerDeviceStatusesInner

// NewGetAppFiles200ResponseDataInnerDeviceStatusesInner instantiates a new GetAppFiles200ResponseDataInnerDeviceStatusesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppFiles200ResponseDataInnerDeviceStatusesInner() *GetAppFiles200ResponseDataInnerDeviceStatusesInner {
	this := GetAppFiles200ResponseDataInnerDeviceStatusesInner{}
	return &this
}

// NewGetAppFiles200ResponseDataInnerDeviceStatusesInnerWithDefaults instantiates a new GetAppFiles200ResponseDataInnerDeviceStatusesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppFiles200ResponseDataInnerDeviceStatusesInnerWithDefaults() *GetAppFiles200ResponseDataInnerDeviceStatusesInner {
	this := GetAppFiles200ResponseDataInnerDeviceStatusesInner{}
	return &this
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) SetStatus(v string) {
	o.Status = &v
}

// GetStatusTimestamp returns the StatusTimestamp field value if set, zero value otherwise.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) GetStatusTimestamp() Time {
	if o == nil || IsNil(o.StatusTimestamp) {
		var ret Time
		return ret
	}
	return *o.StatusTimestamp
}

// GetStatusTimestampOk returns a tuple with the StatusTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) GetStatusTimestampOk() (*Time, bool) {
	if o == nil || IsNil(o.StatusTimestamp) {
		return nil, false
	}
	return o.StatusTimestamp, true
}

// HasStatusTimestamp returns a boolean if a field has been set.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) HasStatusTimestamp() bool {
	if o != nil && !IsNil(o.StatusTimestamp) {
		return true
	}

	return false
}

// SetStatusTimestamp gets a reference to the given Time and assigns it to the StatusTimestamp field.
func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) SetStatusTimestamp(v Time) {
	o.StatusTimestamp = &v
}

func (o GetAppFiles200ResponseDataInnerDeviceStatusesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppFiles200ResponseDataInnerDeviceStatusesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusTimestamp) {
		toSerialize["statusTimestamp"] = o.StatusTimestamp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAppFiles200ResponseDataInnerDeviceStatusesInner) UnmarshalJSON(data []byte) (err error) {
	varGetAppFiles200ResponseDataInnerDeviceStatusesInner := _GetAppFiles200ResponseDataInnerDeviceStatusesInner{}

	err = json.Unmarshal(data, &varGetAppFiles200ResponseDataInnerDeviceStatusesInner)

	if err != nil {
		return err
	}

	*o = GetAppFiles200ResponseDataInnerDeviceStatusesInner(varGetAppFiles200ResponseDataInnerDeviceStatusesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "deviceId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "statusTimestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner struct {
	value *GetAppFiles200ResponseDataInnerDeviceStatusesInner
	isSet bool
}

func (v NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner) Get() *GetAppFiles200ResponseDataInnerDeviceStatusesInner {
	return v.value
}

func (v *NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner) Set(val *GetAppFiles200ResponseDataInnerDeviceStatusesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppFiles200ResponseDataInnerDeviceStatusesInner(val *GetAppFiles200ResponseDataInnerDeviceStatusesInner) *NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner {
	return &NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner{value: val, isSet: true}
}

func (v NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppFiles200ResponseDataInnerDeviceStatusesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


