/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetDeviceReleaseChannels200ResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeviceReleaseChannels200ResponseLinks{}

// GetDeviceReleaseChannels200ResponseLinks struct for GetDeviceReleaseChannels200ResponseLinks
type GetDeviceReleaseChannels200ResponseLinks struct {
	First *string `json:"first,omitempty"`
	Last *string `json:"last,omitempty"`
	Prev NullableString `json:"prev,omitempty"`
	Next NullableString `json:"next,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetDeviceReleaseChannels200ResponseLinks GetDeviceReleaseChannels200ResponseLinks

// NewGetDeviceReleaseChannels200ResponseLinks instantiates a new GetDeviceReleaseChannels200ResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeviceReleaseChannels200ResponseLinks() *GetDeviceReleaseChannels200ResponseLinks {
	this := GetDeviceReleaseChannels200ResponseLinks{}
	return &this
}

// NewGetDeviceReleaseChannels200ResponseLinksWithDefaults instantiates a new GetDeviceReleaseChannels200ResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeviceReleaseChannels200ResponseLinksWithDefaults() *GetDeviceReleaseChannels200ResponseLinks {
	this := GetDeviceReleaseChannels200ResponseLinks{}
	return &this
}

// GetFirst returns the First field value if set, zero value otherwise.
func (o *GetDeviceReleaseChannels200ResponseLinks) GetFirst() string {
	if o == nil || IsNil(o.First) {
		var ret string
		return ret
	}
	return *o.First
}

// GetFirstOk returns a tuple with the First field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeviceReleaseChannels200ResponseLinks) GetFirstOk() (*string, bool) {
	if o == nil || IsNil(o.First) {
		return nil, false
	}
	return o.First, true
}

// HasFirst returns a boolean if a field has been set.
func (o *GetDeviceReleaseChannels200ResponseLinks) HasFirst() bool {
	if o != nil && !IsNil(o.First) {
		return true
	}

	return false
}

// SetFirst gets a reference to the given string and assigns it to the First field.
func (o *GetDeviceReleaseChannels200ResponseLinks) SetFirst(v string) {
	o.First = &v
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *GetDeviceReleaseChannels200ResponseLinks) GetLast() string {
	if o == nil || IsNil(o.Last) {
		var ret string
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeviceReleaseChannels200ResponseLinks) GetLastOk() (*string, bool) {
	if o == nil || IsNil(o.Last) {
		return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *GetDeviceReleaseChannels200ResponseLinks) HasLast() bool {
	if o != nil && !IsNil(o.Last) {
		return true
	}

	return false
}

// SetLast gets a reference to the given string and assigns it to the Last field.
func (o *GetDeviceReleaseChannels200ResponseLinks) SetLast(v string) {
	o.Last = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDeviceReleaseChannels200ResponseLinks) GetPrev() string {
	if o == nil || IsNil(o.Prev.Get()) {
		var ret string
		return ret
	}
	return *o.Prev.Get()
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDeviceReleaseChannels200ResponseLinks) GetPrevOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prev.Get(), o.Prev.IsSet()
}

// HasPrev returns a boolean if a field has been set.
func (o *GetDeviceReleaseChannels200ResponseLinks) HasPrev() bool {
	if o != nil && o.Prev.IsSet() {
		return true
	}

	return false
}

// SetPrev gets a reference to the given NullableString and assigns it to the Prev field.
func (o *GetDeviceReleaseChannels200ResponseLinks) SetPrev(v string) {
	o.Prev.Set(&v)
}
// SetPrevNil sets the value for Prev to be an explicit nil
func (o *GetDeviceReleaseChannels200ResponseLinks) SetPrevNil() {
	o.Prev.Set(nil)
}

// UnsetPrev ensures that no value is present for Prev, not even an explicit nil
func (o *GetDeviceReleaseChannels200ResponseLinks) UnsetPrev() {
	o.Prev.Unset()
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDeviceReleaseChannels200ResponseLinks) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDeviceReleaseChannels200ResponseLinks) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *GetDeviceReleaseChannels200ResponseLinks) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *GetDeviceReleaseChannels200ResponseLinks) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *GetDeviceReleaseChannels200ResponseLinks) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *GetDeviceReleaseChannels200ResponseLinks) UnsetNext() {
	o.Next.Unset()
}

func (o GetDeviceReleaseChannels200ResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeviceReleaseChannels200ResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.First) {
		toSerialize["first"] = o.First
	}
	if !IsNil(o.Last) {
		toSerialize["last"] = o.Last
	}
	if o.Prev.IsSet() {
		toSerialize["prev"] = o.Prev.Get()
	}
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDeviceReleaseChannels200ResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varGetDeviceReleaseChannels200ResponseLinks := _GetDeviceReleaseChannels200ResponseLinks{}

	err = json.Unmarshal(data, &varGetDeviceReleaseChannels200ResponseLinks)

	if err != nil {
		return err
	}

	*o = GetDeviceReleaseChannels200ResponseLinks(varGetDeviceReleaseChannels200ResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "first")
		delete(additionalProperties, "last")
		delete(additionalProperties, "prev")
		delete(additionalProperties, "next")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDeviceReleaseChannels200ResponseLinks struct {
	value *GetDeviceReleaseChannels200ResponseLinks
	isSet bool
}

func (v NullableGetDeviceReleaseChannels200ResponseLinks) Get() *GetDeviceReleaseChannels200ResponseLinks {
	return v.value
}

func (v *NullableGetDeviceReleaseChannels200ResponseLinks) Set(val *GetDeviceReleaseChannels200ResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeviceReleaseChannels200ResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeviceReleaseChannels200ResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeviceReleaseChannels200ResponseLinks(val *GetDeviceReleaseChannels200ResponseLinks) *NullableGetDeviceReleaseChannels200ResponseLinks {
	return &NullableGetDeviceReleaseChannels200ResponseLinks{value: val, isSet: true}
}

func (v NullableGetDeviceReleaseChannels200ResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeviceReleaseChannels200ResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


