/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the InitiateVideoUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiateVideoUploadRequest{}

// InitiateVideoUploadRequest struct for InitiateVideoUploadRequest
type InitiateVideoUploadRequest struct {
	// The original filename of the video. Must end with .mp4, .mkv, or .webm
	Filename string `json:"filename"`
	// The dimensional type of the video
	VideoType string `json:"videoType"`
	// How the 360°/180° video content is mapped. Required for ThreeSixty and OneEighty videos, prohibited for TwoDimensional
	VideoMapping NullableString `json:"videoMapping,omitempty"`
	// Whether the video is stereoscopic (3D) or monoscopic. Required for ThreeSixty and OneEighty videos, prohibited for TwoDimensional
	VideoDisplay NullableString `json:"videoDisplay,omitempty"`
	// How stereoscopic video content is packed. Required if videoDisplay is Stereoscopic
	VideoPacking NullableString `json:"videoPacking,omitempty"`
	// The audio encoding format of the video
	AudioEncoding string `json:"audioEncoding"`
	AdditionalProperties map[string]interface{}
}

type _InitiateVideoUploadRequest InitiateVideoUploadRequest

// NewInitiateVideoUploadRequest instantiates a new InitiateVideoUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiateVideoUploadRequest(filename string, videoType string, audioEncoding string) *InitiateVideoUploadRequest {
	this := InitiateVideoUploadRequest{}
	this.Filename = filename
	this.VideoType = videoType
	this.AudioEncoding = audioEncoding
	return &this
}

// NewInitiateVideoUploadRequestWithDefaults instantiates a new InitiateVideoUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiateVideoUploadRequestWithDefaults() *InitiateVideoUploadRequest {
	this := InitiateVideoUploadRequest{}
	return &this
}

// GetFilename returns the Filename field value
func (o *InitiateVideoUploadRequest) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *InitiateVideoUploadRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *InitiateVideoUploadRequest) SetFilename(v string) {
	o.Filename = v
}

// GetVideoType returns the VideoType field value
func (o *InitiateVideoUploadRequest) GetVideoType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VideoType
}

// GetVideoTypeOk returns a tuple with the VideoType field value
// and a boolean to check if the value has been set.
func (o *InitiateVideoUploadRequest) GetVideoTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VideoType, true
}

// SetVideoType sets field value
func (o *InitiateVideoUploadRequest) SetVideoType(v string) {
	o.VideoType = v
}

// GetVideoMapping returns the VideoMapping field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InitiateVideoUploadRequest) GetVideoMapping() string {
	if o == nil || IsNil(o.VideoMapping.Get()) {
		var ret string
		return ret
	}
	return *o.VideoMapping.Get()
}

// GetVideoMappingOk returns a tuple with the VideoMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InitiateVideoUploadRequest) GetVideoMappingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoMapping.Get(), o.VideoMapping.IsSet()
}

// HasVideoMapping returns a boolean if a field has been set.
func (o *InitiateVideoUploadRequest) HasVideoMapping() bool {
	if o != nil && o.VideoMapping.IsSet() {
		return true
	}

	return false
}

// SetVideoMapping gets a reference to the given NullableString and assigns it to the VideoMapping field.
func (o *InitiateVideoUploadRequest) SetVideoMapping(v string) {
	o.VideoMapping.Set(&v)
}
// SetVideoMappingNil sets the value for VideoMapping to be an explicit nil
func (o *InitiateVideoUploadRequest) SetVideoMappingNil() {
	o.VideoMapping.Set(nil)
}

// UnsetVideoMapping ensures that no value is present for VideoMapping, not even an explicit nil
func (o *InitiateVideoUploadRequest) UnsetVideoMapping() {
	o.VideoMapping.Unset()
}

// GetVideoDisplay returns the VideoDisplay field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InitiateVideoUploadRequest) GetVideoDisplay() string {
	if o == nil || IsNil(o.VideoDisplay.Get()) {
		var ret string
		return ret
	}
	return *o.VideoDisplay.Get()
}

// GetVideoDisplayOk returns a tuple with the VideoDisplay field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InitiateVideoUploadRequest) GetVideoDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoDisplay.Get(), o.VideoDisplay.IsSet()
}

// HasVideoDisplay returns a boolean if a field has been set.
func (o *InitiateVideoUploadRequest) HasVideoDisplay() bool {
	if o != nil && o.VideoDisplay.IsSet() {
		return true
	}

	return false
}

// SetVideoDisplay gets a reference to the given NullableString and assigns it to the VideoDisplay field.
func (o *InitiateVideoUploadRequest) SetVideoDisplay(v string) {
	o.VideoDisplay.Set(&v)
}
// SetVideoDisplayNil sets the value for VideoDisplay to be an explicit nil
func (o *InitiateVideoUploadRequest) SetVideoDisplayNil() {
	o.VideoDisplay.Set(nil)
}

// UnsetVideoDisplay ensures that no value is present for VideoDisplay, not even an explicit nil
func (o *InitiateVideoUploadRequest) UnsetVideoDisplay() {
	o.VideoDisplay.Unset()
}

// GetVideoPacking returns the VideoPacking field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InitiateVideoUploadRequest) GetVideoPacking() string {
	if o == nil || IsNil(o.VideoPacking.Get()) {
		var ret string
		return ret
	}
	return *o.VideoPacking.Get()
}

// GetVideoPackingOk returns a tuple with the VideoPacking field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InitiateVideoUploadRequest) GetVideoPackingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VideoPacking.Get(), o.VideoPacking.IsSet()
}

// HasVideoPacking returns a boolean if a field has been set.
func (o *InitiateVideoUploadRequest) HasVideoPacking() bool {
	if o != nil && o.VideoPacking.IsSet() {
		return true
	}

	return false
}

// SetVideoPacking gets a reference to the given NullableString and assigns it to the VideoPacking field.
func (o *InitiateVideoUploadRequest) SetVideoPacking(v string) {
	o.VideoPacking.Set(&v)
}
// SetVideoPackingNil sets the value for VideoPacking to be an explicit nil
func (o *InitiateVideoUploadRequest) SetVideoPackingNil() {
	o.VideoPacking.Set(nil)
}

// UnsetVideoPacking ensures that no value is present for VideoPacking, not even an explicit nil
func (o *InitiateVideoUploadRequest) UnsetVideoPacking() {
	o.VideoPacking.Unset()
}

// GetAudioEncoding returns the AudioEncoding field value
func (o *InitiateVideoUploadRequest) GetAudioEncoding() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AudioEncoding
}

// GetAudioEncodingOk returns a tuple with the AudioEncoding field value
// and a boolean to check if the value has been set.
func (o *InitiateVideoUploadRequest) GetAudioEncodingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudioEncoding, true
}

// SetAudioEncoding sets field value
func (o *InitiateVideoUploadRequest) SetAudioEncoding(v string) {
	o.AudioEncoding = v
}

func (o InitiateVideoUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiateVideoUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filename"] = o.Filename
	toSerialize["videoType"] = o.VideoType
	if o.VideoMapping.IsSet() {
		toSerialize["videoMapping"] = o.VideoMapping.Get()
	}
	if o.VideoDisplay.IsSet() {
		toSerialize["videoDisplay"] = o.VideoDisplay.Get()
	}
	if o.VideoPacking.IsSet() {
		toSerialize["videoPacking"] = o.VideoPacking.Get()
	}
	toSerialize["audioEncoding"] = o.AudioEncoding

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InitiateVideoUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filename",
		"videoType",
		"audioEncoding",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiateVideoUploadRequest := _InitiateVideoUploadRequest{}

	err = json.Unmarshal(data, &varInitiateVideoUploadRequest)

	if err != nil {
		return err
	}

	*o = InitiateVideoUploadRequest(varInitiateVideoUploadRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filename")
		delete(additionalProperties, "videoType")
		delete(additionalProperties, "videoMapping")
		delete(additionalProperties, "videoDisplay")
		delete(additionalProperties, "videoPacking")
		delete(additionalProperties, "audioEncoding")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInitiateVideoUploadRequest struct {
	value *InitiateVideoUploadRequest
	isSet bool
}

func (v NullableInitiateVideoUploadRequest) Get() *InitiateVideoUploadRequest {
	return v.value
}

func (v *NullableInitiateVideoUploadRequest) Set(val *InitiateVideoUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateVideoUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateVideoUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateVideoUploadRequest(val *InitiateVideoUploadRequest) *NullableInitiateVideoUploadRequest {
	return &NullableInitiateVideoUploadRequest{value: val, isSet: true}
}

func (v NullableInitiateVideoUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateVideoUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


