/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the ConfigureDeviceArborXrHomeHeadsetExperience409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureDeviceArborXrHomeHeadsetExperience409Response{}

// ConfigureDeviceArborXrHomeHeadsetExperience409Response struct for ConfigureDeviceArborXrHomeHeadsetExperience409Response
type ConfigureDeviceArborXrHomeHeadsetExperience409Response struct {
	Message *string `json:"message,omitempty"`
	GroupId *string `json:"groupId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConfigureDeviceArborXrHomeHeadsetExperience409Response ConfigureDeviceArborXrHomeHeadsetExperience409Response

// NewConfigureDeviceArborXrHomeHeadsetExperience409Response instantiates a new ConfigureDeviceArborXrHomeHeadsetExperience409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureDeviceArborXrHomeHeadsetExperience409Response() *ConfigureDeviceArborXrHomeHeadsetExperience409Response {
	this := ConfigureDeviceArborXrHomeHeadsetExperience409Response{}
	return &this
}

// NewConfigureDeviceArborXrHomeHeadsetExperience409ResponseWithDefaults instantiates a new ConfigureDeviceArborXrHomeHeadsetExperience409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureDeviceArborXrHomeHeadsetExperience409ResponseWithDefaults() *ConfigureDeviceArborXrHomeHeadsetExperience409Response {
	this := ConfigureDeviceArborXrHomeHeadsetExperience409Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) SetMessage(v string) {
	o.Message = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) SetGroupId(v string) {
	o.GroupId = &v
}

func (o ConfigureDeviceArborXrHomeHeadsetExperience409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureDeviceArborXrHomeHeadsetExperience409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.GroupId) {
		toSerialize["groupId"] = o.GroupId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigureDeviceArborXrHomeHeadsetExperience409Response) UnmarshalJSON(data []byte) (err error) {
	varConfigureDeviceArborXrHomeHeadsetExperience409Response := _ConfigureDeviceArborXrHomeHeadsetExperience409Response{}

	err = json.Unmarshal(data, &varConfigureDeviceArborXrHomeHeadsetExperience409Response)

	if err != nil {
		return err
	}

	*o = ConfigureDeviceArborXrHomeHeadsetExperience409Response(varConfigureDeviceArborXrHomeHeadsetExperience409Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "groupId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigureDeviceArborXrHomeHeadsetExperience409Response struct {
	value *ConfigureDeviceArborXrHomeHeadsetExperience409Response
	isSet bool
}

func (v NullableConfigureDeviceArborXrHomeHeadsetExperience409Response) Get() *ConfigureDeviceArborXrHomeHeadsetExperience409Response {
	return v.value
}

func (v *NullableConfigureDeviceArborXrHomeHeadsetExperience409Response) Set(val *ConfigureDeviceArborXrHomeHeadsetExperience409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureDeviceArborXrHomeHeadsetExperience409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureDeviceArborXrHomeHeadsetExperience409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureDeviceArborXrHomeHeadsetExperience409Response(val *ConfigureDeviceArborXrHomeHeadsetExperience409Response) *NullableConfigureDeviceArborXrHomeHeadsetExperience409Response {
	return &NullableConfigureDeviceArborXrHomeHeadsetExperience409Response{value: val, isSet: true}
}

func (v NullableConfigureDeviceArborXrHomeHeadsetExperience409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureDeviceArborXrHomeHeadsetExperience409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


