/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigureGroupArborXrHomeHeadsetExperienceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureGroupArborXrHomeHeadsetExperienceRequest{}

// ConfigureGroupArborXrHomeHeadsetExperienceRequest struct for ConfigureGroupArborXrHomeHeadsetExperienceRequest
type ConfigureGroupArborXrHomeHeadsetExperienceRequest struct {
	// Array of content items visible in the ArborXR Home experience
	VisibleContents []ConfigureGroupArborXrHomeHeadsetExperienceRequestVisibleContentsInner `json:"visibleContents"`
	// Language for the headset experience
	Language string `json:"language"`
	// Title displayed in the menu
	MenuTitle string `json:"menuTitle"`
	// UUID of the image to use as menu icon
	MenuIconImageId string `json:"menuIconImageId"`
	// Whether to remove 'Powered by ArborXR' branding
	RemovePoweredByArborXrBranding bool `json:"removePoweredByArborXrBranding"`
	// Array of shortcuts to enable
	Shortcuts []string `json:"shortcuts"`
	// Numeric admin PIN (4-10 digits)
	AdminPin NullableString `json:"adminPin" validate:"regexp=^[0-9]{4,10}$"`
	// Array of tags for categorization
	CategorizationTags []string `json:"categorizationTags"`
	Background ConfigureGroupArborXrHomeHeadsetExperienceRequestBackground `json:"background"`
	// UUID of the theme to apply
	ThemeId string `json:"themeId"`
	SharedModeSettings *ConfigureGroupArborXrHomeHeadsetExperienceRequestSharedModeSettings `json:"sharedModeSettings,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConfigureGroupArborXrHomeHeadsetExperienceRequest ConfigureGroupArborXrHomeHeadsetExperienceRequest

// NewConfigureGroupArborXrHomeHeadsetExperienceRequest instantiates a new ConfigureGroupArborXrHomeHeadsetExperienceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureGroupArborXrHomeHeadsetExperienceRequest(visibleContents []ConfigureGroupArborXrHomeHeadsetExperienceRequestVisibleContentsInner, language string, menuTitle string, menuIconImageId string, removePoweredByArborXrBranding bool, shortcuts []string, adminPin NullableString, categorizationTags []string, background ConfigureGroupArborXrHomeHeadsetExperienceRequestBackground, themeId string) *ConfigureGroupArborXrHomeHeadsetExperienceRequest {
	this := ConfigureGroupArborXrHomeHeadsetExperienceRequest{}
	this.VisibleContents = visibleContents
	this.Language = language
	this.MenuTitle = menuTitle
	this.MenuIconImageId = menuIconImageId
	this.RemovePoweredByArborXrBranding = removePoweredByArborXrBranding
	this.Shortcuts = shortcuts
	this.AdminPin = adminPin
	this.CategorizationTags = categorizationTags
	this.Background = background
	this.ThemeId = themeId
	return &this
}

// NewConfigureGroupArborXrHomeHeadsetExperienceRequestWithDefaults instantiates a new ConfigureGroupArborXrHomeHeadsetExperienceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureGroupArborXrHomeHeadsetExperienceRequestWithDefaults() *ConfigureGroupArborXrHomeHeadsetExperienceRequest {
	this := ConfigureGroupArborXrHomeHeadsetExperienceRequest{}
	return &this
}

// GetVisibleContents returns the VisibleContents field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetVisibleContents() []ConfigureGroupArborXrHomeHeadsetExperienceRequestVisibleContentsInner {
	if o == nil {
		var ret []ConfigureGroupArborXrHomeHeadsetExperienceRequestVisibleContentsInner
		return ret
	}

	return o.VisibleContents
}

// GetVisibleContentsOk returns a tuple with the VisibleContents field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetVisibleContentsOk() ([]ConfigureGroupArborXrHomeHeadsetExperienceRequestVisibleContentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.VisibleContents, true
}

// SetVisibleContents sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetVisibleContents(v []ConfigureGroupArborXrHomeHeadsetExperienceRequestVisibleContentsInner) {
	o.VisibleContents = v
}

// GetLanguage returns the Language field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetLanguage(v string) {
	o.Language = v
}

// GetMenuTitle returns the MenuTitle field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetMenuTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MenuTitle
}

// GetMenuTitleOk returns a tuple with the MenuTitle field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetMenuTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MenuTitle, true
}

// SetMenuTitle sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetMenuTitle(v string) {
	o.MenuTitle = v
}

// GetMenuIconImageId returns the MenuIconImageId field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetMenuIconImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MenuIconImageId
}

// GetMenuIconImageIdOk returns a tuple with the MenuIconImageId field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetMenuIconImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MenuIconImageId, true
}

// SetMenuIconImageId sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetMenuIconImageId(v string) {
	o.MenuIconImageId = v
}

// GetRemovePoweredByArborXrBranding returns the RemovePoweredByArborXrBranding field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetRemovePoweredByArborXrBranding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RemovePoweredByArborXrBranding
}

// GetRemovePoweredByArborXrBrandingOk returns a tuple with the RemovePoweredByArborXrBranding field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetRemovePoweredByArborXrBrandingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemovePoweredByArborXrBranding, true
}

// SetRemovePoweredByArborXrBranding sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetRemovePoweredByArborXrBranding(v bool) {
	o.RemovePoweredByArborXrBranding = v
}

// GetShortcuts returns the Shortcuts field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetShortcuts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Shortcuts
}

// GetShortcutsOk returns a tuple with the Shortcuts field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetShortcutsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Shortcuts, true
}

// SetShortcuts sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetShortcuts(v []string) {
	o.Shortcuts = v
}

// GetAdminPin returns the AdminPin field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetAdminPin() string {
	if o == nil || o.AdminPin.Get() == nil {
		var ret string
		return ret
	}

	return *o.AdminPin.Get()
}

// GetAdminPinOk returns a tuple with the AdminPin field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetAdminPinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AdminPin.Get(), o.AdminPin.IsSet()
}

// SetAdminPin sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetAdminPin(v string) {
	o.AdminPin.Set(&v)
}

// GetCategorizationTags returns the CategorizationTags field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetCategorizationTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CategorizationTags
}

// GetCategorizationTagsOk returns a tuple with the CategorizationTags field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetCategorizationTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CategorizationTags, true
}

// SetCategorizationTags sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetCategorizationTags(v []string) {
	o.CategorizationTags = v
}

// GetBackground returns the Background field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetBackground() ConfigureGroupArborXrHomeHeadsetExperienceRequestBackground {
	if o == nil {
		var ret ConfigureGroupArborXrHomeHeadsetExperienceRequestBackground
		return ret
	}

	return o.Background
}

// GetBackgroundOk returns a tuple with the Background field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetBackgroundOk() (*ConfigureGroupArborXrHomeHeadsetExperienceRequestBackground, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Background, true
}

// SetBackground sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetBackground(v ConfigureGroupArborXrHomeHeadsetExperienceRequestBackground) {
	o.Background = v
}

// GetThemeId returns the ThemeId field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetThemeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThemeId
}

// GetThemeIdOk returns a tuple with the ThemeId field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetThemeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThemeId, true
}

// SetThemeId sets field value
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetThemeId(v string) {
	o.ThemeId = v
}

// GetSharedModeSettings returns the SharedModeSettings field value if set, zero value otherwise.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetSharedModeSettings() ConfigureGroupArborXrHomeHeadsetExperienceRequestSharedModeSettings {
	if o == nil || IsNil(o.SharedModeSettings) {
		var ret ConfigureGroupArborXrHomeHeadsetExperienceRequestSharedModeSettings
		return ret
	}
	return *o.SharedModeSettings
}

// GetSharedModeSettingsOk returns a tuple with the SharedModeSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) GetSharedModeSettingsOk() (*ConfigureGroupArborXrHomeHeadsetExperienceRequestSharedModeSettings, bool) {
	if o == nil || IsNil(o.SharedModeSettings) {
		return nil, false
	}
	return o.SharedModeSettings, true
}

// HasSharedModeSettings returns a boolean if a field has been set.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) HasSharedModeSettings() bool {
	if o != nil && !IsNil(o.SharedModeSettings) {
		return true
	}

	return false
}

// SetSharedModeSettings gets a reference to the given ConfigureGroupArborXrHomeHeadsetExperienceRequestSharedModeSettings and assigns it to the SharedModeSettings field.
func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) SetSharedModeSettings(v ConfigureGroupArborXrHomeHeadsetExperienceRequestSharedModeSettings) {
	o.SharedModeSettings = &v
}

func (o ConfigureGroupArborXrHomeHeadsetExperienceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureGroupArborXrHomeHeadsetExperienceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["visibleContents"] = o.VisibleContents
	toSerialize["language"] = o.Language
	toSerialize["menuTitle"] = o.MenuTitle
	toSerialize["menuIconImageId"] = o.MenuIconImageId
	toSerialize["removePoweredByArborXrBranding"] = o.RemovePoweredByArborXrBranding
	toSerialize["shortcuts"] = o.Shortcuts
	toSerialize["adminPin"] = o.AdminPin.Get()
	toSerialize["categorizationTags"] = o.CategorizationTags
	toSerialize["background"] = o.Background
	toSerialize["themeId"] = o.ThemeId
	if !IsNil(o.SharedModeSettings) {
		toSerialize["sharedModeSettings"] = o.SharedModeSettings
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigureGroupArborXrHomeHeadsetExperienceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"visibleContents",
		"language",
		"menuTitle",
		"menuIconImageId",
		"removePoweredByArborXrBranding",
		"shortcuts",
		"adminPin",
		"categorizationTags",
		"background",
		"themeId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigureGroupArborXrHomeHeadsetExperienceRequest := _ConfigureGroupArborXrHomeHeadsetExperienceRequest{}

	err = json.Unmarshal(data, &varConfigureGroupArborXrHomeHeadsetExperienceRequest)

	if err != nil {
		return err
	}

	*o = ConfigureGroupArborXrHomeHeadsetExperienceRequest(varConfigureGroupArborXrHomeHeadsetExperienceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "visibleContents")
		delete(additionalProperties, "language")
		delete(additionalProperties, "menuTitle")
		delete(additionalProperties, "menuIconImageId")
		delete(additionalProperties, "removePoweredByArborXrBranding")
		delete(additionalProperties, "shortcuts")
		delete(additionalProperties, "adminPin")
		delete(additionalProperties, "categorizationTags")
		delete(additionalProperties, "background")
		delete(additionalProperties, "themeId")
		delete(additionalProperties, "sharedModeSettings")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigureGroupArborXrHomeHeadsetExperienceRequest struct {
	value *ConfigureGroupArborXrHomeHeadsetExperienceRequest
	isSet bool
}

func (v NullableConfigureGroupArborXrHomeHeadsetExperienceRequest) Get() *ConfigureGroupArborXrHomeHeadsetExperienceRequest {
	return v.value
}

func (v *NullableConfigureGroupArborXrHomeHeadsetExperienceRequest) Set(val *ConfigureGroupArborXrHomeHeadsetExperienceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureGroupArborXrHomeHeadsetExperienceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureGroupArborXrHomeHeadsetExperienceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureGroupArborXrHomeHeadsetExperienceRequest(val *ConfigureGroupArborXrHomeHeadsetExperienceRequest) *NullableConfigureGroupArborXrHomeHeadsetExperienceRequest {
	return &NullableConfigureGroupArborXrHomeHeadsetExperienceRequest{value: val, isSet: true}
}

func (v NullableConfigureGroupArborXrHomeHeadsetExperienceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureGroupArborXrHomeHeadsetExperienceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


