/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetCurrentUser200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCurrentUser200Response{}

// GetCurrentUser200Response struct for GetCurrentUser200Response
type GetCurrentUser200Response struct {
	Id *string `json:"id,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	Email *string `json:"email,omitempty"`
	AccessControls []GetCurrentUser200ResponseAccessControlsInner `json:"accessControls,omitempty"`
	CreatedAt *Time `json:"createdAt,omitempty"`
	UpdatedAt *Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetCurrentUser200Response GetCurrentUser200Response

// NewGetCurrentUser200Response instantiates a new GetCurrentUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCurrentUser200Response() *GetCurrentUser200Response {
	this := GetCurrentUser200Response{}
	return &this
}

// NewGetCurrentUser200ResponseWithDefaults instantiates a new GetCurrentUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCurrentUser200ResponseWithDefaults() *GetCurrentUser200Response {
	this := GetCurrentUser200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetCurrentUser200Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUser200Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetCurrentUser200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetCurrentUser200Response) SetId(v string) {
	o.Id = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *GetCurrentUser200Response) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUser200Response) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *GetCurrentUser200Response) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *GetCurrentUser200Response) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *GetCurrentUser200Response) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUser200Response) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *GetCurrentUser200Response) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *GetCurrentUser200Response) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GetCurrentUser200Response) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUser200Response) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GetCurrentUser200Response) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GetCurrentUser200Response) SetEmail(v string) {
	o.Email = &v
}

// GetAccessControls returns the AccessControls field value if set, zero value otherwise.
func (o *GetCurrentUser200Response) GetAccessControls() []GetCurrentUser200ResponseAccessControlsInner {
	if o == nil || IsNil(o.AccessControls) {
		var ret []GetCurrentUser200ResponseAccessControlsInner
		return ret
	}
	return o.AccessControls
}

// GetAccessControlsOk returns a tuple with the AccessControls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUser200Response) GetAccessControlsOk() ([]GetCurrentUser200ResponseAccessControlsInner, bool) {
	if o == nil || IsNil(o.AccessControls) {
		return nil, false
	}
	return o.AccessControls, true
}

// HasAccessControls returns a boolean if a field has been set.
func (o *GetCurrentUser200Response) HasAccessControls() bool {
	if o != nil && !IsNil(o.AccessControls) {
		return true
	}

	return false
}

// SetAccessControls gets a reference to the given []GetCurrentUser200ResponseAccessControlsInner and assigns it to the AccessControls field.
func (o *GetCurrentUser200Response) SetAccessControls(v []GetCurrentUser200ResponseAccessControlsInner) {
	o.AccessControls = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetCurrentUser200Response) GetCreatedAt() Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUser200Response) GetCreatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetCurrentUser200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given Time and assigns it to the CreatedAt field.
func (o *GetCurrentUser200Response) SetCreatedAt(v Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetCurrentUser200Response) GetUpdatedAt() Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUser200Response) GetUpdatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetCurrentUser200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given Time and assigns it to the UpdatedAt field.
func (o *GetCurrentUser200Response) SetUpdatedAt(v Time) {
	o.UpdatedAt = &v
}

func (o GetCurrentUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCurrentUser200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.AccessControls) {
		toSerialize["accessControls"] = o.AccessControls
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCurrentUser200Response) UnmarshalJSON(data []byte) (err error) {
	varGetCurrentUser200Response := _GetCurrentUser200Response{}

	err = json.Unmarshal(data, &varGetCurrentUser200Response)

	if err != nil {
		return err
	}

	*o = GetCurrentUser200Response(varGetCurrentUser200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "email")
		delete(additionalProperties, "accessControls")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCurrentUser200Response struct {
	value *GetCurrentUser200Response
	isSet bool
}

func (v NullableGetCurrentUser200Response) Get() *GetCurrentUser200Response {
	return v.value
}

func (v *NullableGetCurrentUser200Response) Set(val *GetCurrentUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCurrentUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCurrentUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCurrentUser200Response(val *GetCurrentUser200Response) *NullableGetCurrentUser200Response {
	return &NullableGetCurrentUser200Response{value: val, isSet: true}
}

func (v NullableGetCurrentUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCurrentUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


