/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetGroupHeadsetExperience200ResponseOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGroupHeadsetExperience200ResponseOneOf2{}

// GetGroupHeadsetExperience200ResponseOneOf2 struct for GetGroupHeadsetExperience200ResponseOneOf2
type GetGroupHeadsetExperience200ResponseOneOf2 struct {
	Id NullableString `json:"id"`
	Mode string `json:"mode"`
	MetaHmsSettings GetGroupHeadsetExperience200ResponseOneOf2MetaHmsSettings `json:"metaHmsSettings"`
	CreatedAt NullableTime `json:"createdAt"`
	UpdatedAt NullableTime `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _GetGroupHeadsetExperience200ResponseOneOf2 GetGroupHeadsetExperience200ResponseOneOf2

// NewGetGroupHeadsetExperience200ResponseOneOf2 instantiates a new GetGroupHeadsetExperience200ResponseOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGroupHeadsetExperience200ResponseOneOf2(id NullableString, mode string, metaHmsSettings GetGroupHeadsetExperience200ResponseOneOf2MetaHmsSettings, createdAt NullableTime, updatedAt NullableTime) *GetGroupHeadsetExperience200ResponseOneOf2 {
	this := GetGroupHeadsetExperience200ResponseOneOf2{}
	this.Id = id
	this.Mode = mode
	this.MetaHmsSettings = metaHmsSettings
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetGroupHeadsetExperience200ResponseOneOf2WithDefaults instantiates a new GetGroupHeadsetExperience200ResponseOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGroupHeadsetExperience200ResponseOneOf2WithDefaults() *GetGroupHeadsetExperience200ResponseOneOf2 {
	this := GetGroupHeadsetExperience200ResponseOneOf2{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}

	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// SetId sets field value
func (o *GetGroupHeadsetExperience200ResponseOneOf2) SetId(v string) {
	o.Id.Set(&v)
}

// GetMode returns the Mode field value
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *GetGroupHeadsetExperience200ResponseOneOf2) SetMode(v string) {
	o.Mode = v
}

// GetMetaHmsSettings returns the MetaHmsSettings field value
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetMetaHmsSettings() GetGroupHeadsetExperience200ResponseOneOf2MetaHmsSettings {
	if o == nil {
		var ret GetGroupHeadsetExperience200ResponseOneOf2MetaHmsSettings
		return ret
	}

	return o.MetaHmsSettings
}

// GetMetaHmsSettingsOk returns a tuple with the MetaHmsSettings field value
// and a boolean to check if the value has been set.
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetMetaHmsSettingsOk() (*GetGroupHeadsetExperience200ResponseOneOf2MetaHmsSettings, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetaHmsSettings, true
}

// SetMetaHmsSettings sets field value
func (o *GetGroupHeadsetExperience200ResponseOneOf2) SetMetaHmsSettings(v GetGroupHeadsetExperience200ResponseOneOf2MetaHmsSettings) {
	o.MetaHmsSettings = v
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for Time will be returned
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetCreatedAt() Time {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret Time
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetCreatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *GetGroupHeadsetExperience200ResponseOneOf2) SetCreatedAt(v Time) {
	o.CreatedAt.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for Time will be returned
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetUpdatedAt() Time {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret Time
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupHeadsetExperience200ResponseOneOf2) GetUpdatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *GetGroupHeadsetExperience200ResponseOneOf2) SetUpdatedAt(v Time) {
	o.UpdatedAt.Set(&v)
}

func (o GetGroupHeadsetExperience200ResponseOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGroupHeadsetExperience200ResponseOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id.Get()
	toSerialize["mode"] = o.Mode
	toSerialize["metaHmsSettings"] = o.MetaHmsSettings
	toSerialize["createdAt"] = o.CreatedAt.Get()
	toSerialize["updatedAt"] = o.UpdatedAt.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetGroupHeadsetExperience200ResponseOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"mode",
		"metaHmsSettings",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetGroupHeadsetExperience200ResponseOneOf2 := _GetGroupHeadsetExperience200ResponseOneOf2{}

	err = json.Unmarshal(data, &varGetGroupHeadsetExperience200ResponseOneOf2)

	if err != nil {
		return err
	}

	*o = GetGroupHeadsetExperience200ResponseOneOf2(varGetGroupHeadsetExperience200ResponseOneOf2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "mode")
		delete(additionalProperties, "metaHmsSettings")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetGroupHeadsetExperience200ResponseOneOf2 struct {
	value *GetGroupHeadsetExperience200ResponseOneOf2
	isSet bool
}

func (v NullableGetGroupHeadsetExperience200ResponseOneOf2) Get() *GetGroupHeadsetExperience200ResponseOneOf2 {
	return v.value
}

func (v *NullableGetGroupHeadsetExperience200ResponseOneOf2) Set(val *GetGroupHeadsetExperience200ResponseOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGroupHeadsetExperience200ResponseOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGroupHeadsetExperience200ResponseOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGroupHeadsetExperience200ResponseOneOf2(val *GetGroupHeadsetExperience200ResponseOneOf2) *NullableGetGroupHeadsetExperience200ResponseOneOf2 {
	return &NullableGetGroupHeadsetExperience200ResponseOneOf2{value: val, isSet: true}
}

func (v NullableGetGroupHeadsetExperience200ResponseOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGroupHeadsetExperience200ResponseOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


