/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner{}

// GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner struct for GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner
type GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner struct {
	Type string `json:"type"`
	Id string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner

// NewGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner instantiates a new GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner(type_ string, id string) *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner {
	this := GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewGetGroupDeviceExperience200ResponseOneOfVisibleContentsInnerWithDefaults instantiates a new GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGroupDeviceExperience200ResponseOneOfVisibleContentsInnerWithDefaults() *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner {
	this := GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner{}
	return &this
}

// GetType returns the Type field value
func (o *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) SetId(v string) {
	o.Id = v
}

func (o GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner := _GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner{}

	err = json.Unmarshal(data, &varGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner)

	if err != nil {
		return err
	}

	*o = GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner(varGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner struct {
	value *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner
	isSet bool
}

func (v NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) Get() *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner {
	return v.value
}

func (v *NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) Set(val *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner(val *GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) *NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner {
	return &NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner{value: val, isSet: true}
}

func (v NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


