/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetStatuses200ResponseDataInnerContentOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStatuses200ResponseDataInnerContentOneOf5{}

// GetStatuses200ResponseDataInnerContentOneOf5 struct for GetStatuses200ResponseDataInnerContentOneOf5
type GetStatuses200ResponseDataInnerContentOneOf5 struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Name NullableString `json:"name"`
	Ssid NullableString `json:"ssid"`
	AdditionalProperties map[string]interface{}
}

type _GetStatuses200ResponseDataInnerContentOneOf5 GetStatuses200ResponseDataInnerContentOneOf5

// NewGetStatuses200ResponseDataInnerContentOneOf5 instantiates a new GetStatuses200ResponseDataInnerContentOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatuses200ResponseDataInnerContentOneOf5(type_ string, id string, name NullableString, ssid NullableString) *GetStatuses200ResponseDataInnerContentOneOf5 {
	this := GetStatuses200ResponseDataInnerContentOneOf5{}
	this.Type = type_
	this.Id = id
	this.Name = name
	this.Ssid = ssid
	return &this
}

// NewGetStatuses200ResponseDataInnerContentOneOf5WithDefaults instantiates a new GetStatuses200ResponseDataInnerContentOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatuses200ResponseDataInnerContentOneOf5WithDefaults() *GetStatuses200ResponseDataInnerContentOneOf5 {
	this := GetStatuses200ResponseDataInnerContentOneOf5{}
	return &this
}

// GetType returns the Type field value
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetStatuses200ResponseDataInnerContentOneOf5) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetStatuses200ResponseDataInnerContentOneOf5) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *GetStatuses200ResponseDataInnerContentOneOf5) SetName(v string) {
	o.Name.Set(&v)
}

// GetSsid returns the Ssid field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetSsid() string {
	if o == nil || o.Ssid.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ssid.Get()
}

// GetSsidOk returns a tuple with the Ssid field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetStatuses200ResponseDataInnerContentOneOf5) GetSsidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ssid.Get(), o.Ssid.IsSet()
}

// SetSsid sets field value
func (o *GetStatuses200ResponseDataInnerContentOneOf5) SetSsid(v string) {
	o.Ssid.Set(&v)
}

func (o GetStatuses200ResponseDataInnerContentOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStatuses200ResponseDataInnerContentOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name.Get()
	toSerialize["ssid"] = o.Ssid.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetStatuses200ResponseDataInnerContentOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"name",
		"ssid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetStatuses200ResponseDataInnerContentOneOf5 := _GetStatuses200ResponseDataInnerContentOneOf5{}

	err = json.Unmarshal(data, &varGetStatuses200ResponseDataInnerContentOneOf5)

	if err != nil {
		return err
	}

	*o = GetStatuses200ResponseDataInnerContentOneOf5(varGetStatuses200ResponseDataInnerContentOneOf5)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "ssid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetStatuses200ResponseDataInnerContentOneOf5 struct {
	value *GetStatuses200ResponseDataInnerContentOneOf5
	isSet bool
}

func (v NullableGetStatuses200ResponseDataInnerContentOneOf5) Get() *GetStatuses200ResponseDataInnerContentOneOf5 {
	return v.value
}

func (v *NullableGetStatuses200ResponseDataInnerContentOneOf5) Set(val *GetStatuses200ResponseDataInnerContentOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatuses200ResponseDataInnerContentOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatuses200ResponseDataInnerContentOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatuses200ResponseDataInnerContentOneOf5(val *GetStatuses200ResponseDataInnerContentOneOf5) *NullableGetStatuses200ResponseDataInnerContentOneOf5 {
	return &NullableGetStatuses200ResponseDataInnerContentOneOf5{value: val, isSet: true}
}

func (v NullableGetStatuses200ResponseDataInnerContentOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatuses200ResponseDataInnerContentOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


