/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetCurrentOrganization200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCurrentOrganization200Response{}

// GetCurrentOrganization200Response struct for GetCurrentOrganization200Response
type GetCurrentOrganization200Response struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
	CreatedAt *Time `json:"createdAt,omitempty"`
	UpdatedAt *Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetCurrentOrganization200Response GetCurrentOrganization200Response

// NewGetCurrentOrganization200Response instantiates a new GetCurrentOrganization200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCurrentOrganization200Response() *GetCurrentOrganization200Response {
	this := GetCurrentOrganization200Response{}
	return &this
}

// NewGetCurrentOrganization200ResponseWithDefaults instantiates a new GetCurrentOrganization200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCurrentOrganization200ResponseWithDefaults() *GetCurrentOrganization200Response {
	this := GetCurrentOrganization200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetCurrentOrganization200Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentOrganization200Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetCurrentOrganization200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetCurrentOrganization200Response) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetCurrentOrganization200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentOrganization200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetCurrentOrganization200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetCurrentOrganization200Response) SetName(v string) {
	o.Name = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *GetCurrentOrganization200Response) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentOrganization200Response) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *GetCurrentOrganization200Response) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *GetCurrentOrganization200Response) SetSlug(v string) {
	o.Slug = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetCurrentOrganization200Response) GetCreatedAt() Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentOrganization200Response) GetCreatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetCurrentOrganization200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given Time and assigns it to the CreatedAt field.
func (o *GetCurrentOrganization200Response) SetCreatedAt(v Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetCurrentOrganization200Response) GetUpdatedAt() Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentOrganization200Response) GetUpdatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetCurrentOrganization200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given Time and assigns it to the UpdatedAt field.
func (o *GetCurrentOrganization200Response) SetUpdatedAt(v Time) {
	o.UpdatedAt = &v
}

func (o GetCurrentOrganization200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCurrentOrganization200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCurrentOrganization200Response) UnmarshalJSON(data []byte) (err error) {
	varGetCurrentOrganization200Response := _GetCurrentOrganization200Response{}

	err = json.Unmarshal(data, &varGetCurrentOrganization200Response)

	if err != nil {
		return err
	}

	*o = GetCurrentOrganization200Response(varGetCurrentOrganization200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCurrentOrganization200Response struct {
	value *GetCurrentOrganization200Response
	isSet bool
}

func (v NullableGetCurrentOrganization200Response) Get() *GetCurrentOrganization200Response {
	return v.value
}

func (v *NullableGetCurrentOrganization200Response) Set(val *GetCurrentOrganization200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCurrentOrganization200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCurrentOrganization200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCurrentOrganization200Response(val *GetCurrentOrganization200Response) *NullableGetCurrentOrganization200Response {
	return &NullableGetCurrentOrganization200Response{value: val, isSet: true}
}

func (v NullableGetCurrentOrganization200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCurrentOrganization200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


