/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the CreateAppBundle201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAppBundle201Response{}

// CreateAppBundle201Response struct for CreateAppBundle201Response
type CreateAppBundle201Response struct {
	// Unique identifier for the app bundle
	Id *string `json:"id,omitempty"`
	// Auto-generated label of the app bundle. First bundle has no label, subsequent bundles get 'Original' and 'Copy N' labels.
	Label NullableString `json:"label,omitempty"`
	// Current status of the app bundle
	Status *string `json:"status,omitempty"`
	AppBuild *CreateAppBundle201ResponseAppBuild `json:"appBuild,omitempty"`
	// Timestamp when the bundle was created
	CreatedAt *Time `json:"createdAt,omitempty"`
	// Timestamp when the bundle was last updated
	UpdatedAt *Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAppBundle201Response CreateAppBundle201Response

// NewCreateAppBundle201Response instantiates a new CreateAppBundle201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAppBundle201Response() *CreateAppBundle201Response {
	this := CreateAppBundle201Response{}
	return &this
}

// NewCreateAppBundle201ResponseWithDefaults instantiates a new CreateAppBundle201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAppBundle201ResponseWithDefaults() *CreateAppBundle201Response {
	this := CreateAppBundle201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateAppBundle201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppBundle201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateAppBundle201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateAppBundle201Response) SetId(v string) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAppBundle201Response) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAppBundle201Response) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *CreateAppBundle201Response) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *CreateAppBundle201Response) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *CreateAppBundle201Response) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *CreateAppBundle201Response) UnsetLabel() {
	o.Label.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateAppBundle201Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppBundle201Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateAppBundle201Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateAppBundle201Response) SetStatus(v string) {
	o.Status = &v
}

// GetAppBuild returns the AppBuild field value if set, zero value otherwise.
func (o *CreateAppBundle201Response) GetAppBuild() CreateAppBundle201ResponseAppBuild {
	if o == nil || IsNil(o.AppBuild) {
		var ret CreateAppBundle201ResponseAppBuild
		return ret
	}
	return *o.AppBuild
}

// GetAppBuildOk returns a tuple with the AppBuild field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppBundle201Response) GetAppBuildOk() (*CreateAppBundle201ResponseAppBuild, bool) {
	if o == nil || IsNil(o.AppBuild) {
		return nil, false
	}
	return o.AppBuild, true
}

// HasAppBuild returns a boolean if a field has been set.
func (o *CreateAppBundle201Response) HasAppBuild() bool {
	if o != nil && !IsNil(o.AppBuild) {
		return true
	}

	return false
}

// SetAppBuild gets a reference to the given CreateAppBundle201ResponseAppBuild and assigns it to the AppBuild field.
func (o *CreateAppBundle201Response) SetAppBuild(v CreateAppBundle201ResponseAppBuild) {
	o.AppBuild = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CreateAppBundle201Response) GetCreatedAt() Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppBundle201Response) GetCreatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreateAppBundle201Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given Time and assigns it to the CreatedAt field.
func (o *CreateAppBundle201Response) SetCreatedAt(v Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CreateAppBundle201Response) GetUpdatedAt() Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppBundle201Response) GetUpdatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CreateAppBundle201Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given Time and assigns it to the UpdatedAt field.
func (o *CreateAppBundle201Response) SetUpdatedAt(v Time) {
	o.UpdatedAt = &v
}

func (o CreateAppBundle201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAppBundle201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.AppBuild) {
		toSerialize["appBuild"] = o.AppBuild
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAppBundle201Response) UnmarshalJSON(data []byte) (err error) {
	varCreateAppBundle201Response := _CreateAppBundle201Response{}

	err = json.Unmarshal(data, &varCreateAppBundle201Response)

	if err != nil {
		return err
	}

	*o = CreateAppBundle201Response(varCreateAppBundle201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "label")
		delete(additionalProperties, "status")
		delete(additionalProperties, "appBuild")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAppBundle201Response struct {
	value *CreateAppBundle201Response
	isSet bool
}

func (v NullableCreateAppBundle201Response) Get() *CreateAppBundle201Response {
	return v.value
}

func (v *NullableCreateAppBundle201Response) Set(val *CreateAppBundle201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAppBundle201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAppBundle201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAppBundle201Response(val *CreateAppBundle201Response) *NullableCreateAppBundle201Response {
	return &NullableCreateAppBundle201Response{value: val, isSet: true}
}

func (v NullableCreateAppBundle201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAppBundle201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


