/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetGroupDeviceExperience200ResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGroupDeviceExperience200ResponseOneOf1{}

// GetGroupDeviceExperience200ResponseOneOf1 struct for GetGroupDeviceExperience200ResponseOneOf1
type GetGroupDeviceExperience200ResponseOneOf1 struct {
	Id string `json:"id"`
	Mode string `json:"mode"`
	LauncherContent NullableGetGroupDeviceExperience200ResponseOneOf1LauncherContent `json:"launcherContent"`
	VisibleContents []GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner `json:"visibleContents"`
	CreatedAt Time `json:"createdAt"`
	UpdatedAt Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _GetGroupDeviceExperience200ResponseOneOf1 GetGroupDeviceExperience200ResponseOneOf1

// NewGetGroupDeviceExperience200ResponseOneOf1 instantiates a new GetGroupDeviceExperience200ResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGroupDeviceExperience200ResponseOneOf1(id string, mode string, launcherContent NullableGetGroupDeviceExperience200ResponseOneOf1LauncherContent, visibleContents []GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner, createdAt Time, updatedAt Time) *GetGroupDeviceExperience200ResponseOneOf1 {
	this := GetGroupDeviceExperience200ResponseOneOf1{}
	this.Id = id
	this.Mode = mode
	this.LauncherContent = launcherContent
	this.VisibleContents = visibleContents
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetGroupDeviceExperience200ResponseOneOf1WithDefaults instantiates a new GetGroupDeviceExperience200ResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGroupDeviceExperience200ResponseOneOf1WithDefaults() *GetGroupDeviceExperience200ResponseOneOf1 {
	this := GetGroupDeviceExperience200ResponseOneOf1{}
	return &this
}

// GetId returns the Id field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) SetId(v string) {
	o.Id = v
}

// GetMode returns the Mode field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) SetMode(v string) {
	o.Mode = v
}

// GetLauncherContent returns the LauncherContent field value
// If the value is explicit nil, the zero value for GetGroupDeviceExperience200ResponseOneOf1LauncherContent will be returned
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetLauncherContent() GetGroupDeviceExperience200ResponseOneOf1LauncherContent {
	if o == nil || o.LauncherContent.Get() == nil {
		var ret GetGroupDeviceExperience200ResponseOneOf1LauncherContent
		return ret
	}

	return *o.LauncherContent.Get()
}

// GetLauncherContentOk returns a tuple with the LauncherContent field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetLauncherContentOk() (*GetGroupDeviceExperience200ResponseOneOf1LauncherContent, bool) {
	if o == nil {
		return nil, false
	}
	return o.LauncherContent.Get(), o.LauncherContent.IsSet()
}

// SetLauncherContent sets field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) SetLauncherContent(v GetGroupDeviceExperience200ResponseOneOf1LauncherContent) {
	o.LauncherContent.Set(&v)
}

// GetVisibleContents returns the VisibleContents field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetVisibleContents() []GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner {
	if o == nil {
		var ret []GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner
		return ret
	}

	return o.VisibleContents
}

// GetVisibleContentsOk returns a tuple with the VisibleContents field value
// and a boolean to check if the value has been set.
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetVisibleContentsOk() ([]GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.VisibleContents, true
}

// SetVisibleContents sets field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) SetVisibleContents(v []GetGroupDeviceExperience200ResponseOneOfVisibleContentsInner) {
	o.VisibleContents = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetCreatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetCreatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) SetCreatedAt(v Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetUpdatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetGroupDeviceExperience200ResponseOneOf1) GetUpdatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetGroupDeviceExperience200ResponseOneOf1) SetUpdatedAt(v Time) {
	o.UpdatedAt = v
}

func (o GetGroupDeviceExperience200ResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGroupDeviceExperience200ResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["mode"] = o.Mode
	toSerialize["launcherContent"] = o.LauncherContent.Get()
	toSerialize["visibleContents"] = o.VisibleContents
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetGroupDeviceExperience200ResponseOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"mode",
		"launcherContent",
		"visibleContents",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetGroupDeviceExperience200ResponseOneOf1 := _GetGroupDeviceExperience200ResponseOneOf1{}

	err = json.Unmarshal(data, &varGetGroupDeviceExperience200ResponseOneOf1)

	if err != nil {
		return err
	}

	*o = GetGroupDeviceExperience200ResponseOneOf1(varGetGroupDeviceExperience200ResponseOneOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "mode")
		delete(additionalProperties, "launcherContent")
		delete(additionalProperties, "visibleContents")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetGroupDeviceExperience200ResponseOneOf1 struct {
	value *GetGroupDeviceExperience200ResponseOneOf1
	isSet bool
}

func (v NullableGetGroupDeviceExperience200ResponseOneOf1) Get() *GetGroupDeviceExperience200ResponseOneOf1 {
	return v.value
}

func (v *NullableGetGroupDeviceExperience200ResponseOneOf1) Set(val *GetGroupDeviceExperience200ResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGroupDeviceExperience200ResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGroupDeviceExperience200ResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGroupDeviceExperience200ResponseOneOf1(val *GetGroupDeviceExperience200ResponseOneOf1) *NullableGetGroupDeviceExperience200ResponseOneOf1 {
	return &NullableGetGroupDeviceExperience200ResponseOneOf1{value: val, isSet: true}
}

func (v NullableGetGroupDeviceExperience200ResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGroupDeviceExperience200ResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


