/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetStatuses200ResponseDataInnerContentOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStatuses200ResponseDataInnerContentOneOf1{}

// GetStatuses200ResponseDataInnerContentOneOf1 struct for GetStatuses200ResponseDataInnerContentOneOf1
type GetStatuses200ResponseDataInnerContentOneOf1 struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Name NullableString `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _GetStatuses200ResponseDataInnerContentOneOf1 GetStatuses200ResponseDataInnerContentOneOf1

// NewGetStatuses200ResponseDataInnerContentOneOf1 instantiates a new GetStatuses200ResponseDataInnerContentOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatuses200ResponseDataInnerContentOneOf1(type_ string, id string, name NullableString) *GetStatuses200ResponseDataInnerContentOneOf1 {
	this := GetStatuses200ResponseDataInnerContentOneOf1{}
	this.Type = type_
	this.Id = id
	this.Name = name
	return &this
}

// NewGetStatuses200ResponseDataInnerContentOneOf1WithDefaults instantiates a new GetStatuses200ResponseDataInnerContentOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatuses200ResponseDataInnerContentOneOf1WithDefaults() *GetStatuses200ResponseDataInnerContentOneOf1 {
	this := GetStatuses200ResponseDataInnerContentOneOf1{}
	return &this
}

// GetType returns the Type field value
func (o *GetStatuses200ResponseDataInnerContentOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetStatuses200ResponseDataInnerContentOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetStatuses200ResponseDataInnerContentOneOf1) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GetStatuses200ResponseDataInnerContentOneOf1) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetStatuses200ResponseDataInnerContentOneOf1) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetStatuses200ResponseDataInnerContentOneOf1) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetStatuses200ResponseDataInnerContentOneOf1) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetStatuses200ResponseDataInnerContentOneOf1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *GetStatuses200ResponseDataInnerContentOneOf1) SetName(v string) {
	o.Name.Set(&v)
}

func (o GetStatuses200ResponseDataInnerContentOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStatuses200ResponseDataInnerContentOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetStatuses200ResponseDataInnerContentOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetStatuses200ResponseDataInnerContentOneOf1 := _GetStatuses200ResponseDataInnerContentOneOf1{}

	err = json.Unmarshal(data, &varGetStatuses200ResponseDataInnerContentOneOf1)

	if err != nil {
		return err
	}

	*o = GetStatuses200ResponseDataInnerContentOneOf1(varGetStatuses200ResponseDataInnerContentOneOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetStatuses200ResponseDataInnerContentOneOf1 struct {
	value *GetStatuses200ResponseDataInnerContentOneOf1
	isSet bool
}

func (v NullableGetStatuses200ResponseDataInnerContentOneOf1) Get() *GetStatuses200ResponseDataInnerContentOneOf1 {
	return v.value
}

func (v *NullableGetStatuses200ResponseDataInnerContentOneOf1) Set(val *GetStatuses200ResponseDataInnerContentOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatuses200ResponseDataInnerContentOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatuses200ResponseDataInnerContentOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatuses200ResponseDataInnerContentOneOf1(val *GetStatuses200ResponseDataInnerContentOneOf1) *NullableGetStatuses200ResponseDataInnerContentOneOf1 {
	return &NullableGetStatuses200ResponseDataInnerContentOneOf1{value: val, isSet: true}
}

func (v NullableGetStatuses200ResponseDataInnerContentOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatuses200ResponseDataInnerContentOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


