/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PreSignVideoUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreSignVideoUploadRequest{}

// PreSignVideoUploadRequest struct for PreSignVideoUploadRequest
type PreSignVideoUploadRequest struct {
	Key string `json:"key"`
	UploadId string `json:"uploadId"`
	PartNumbers []int32 `json:"partNumbers"`
	AdditionalProperties map[string]interface{}
}

type _PreSignVideoUploadRequest PreSignVideoUploadRequest

// NewPreSignVideoUploadRequest instantiates a new PreSignVideoUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreSignVideoUploadRequest(key string, uploadId string, partNumbers []int32) *PreSignVideoUploadRequest {
	this := PreSignVideoUploadRequest{}
	this.Key = key
	this.UploadId = uploadId
	this.PartNumbers = partNumbers
	return &this
}

// NewPreSignVideoUploadRequestWithDefaults instantiates a new PreSignVideoUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreSignVideoUploadRequestWithDefaults() *PreSignVideoUploadRequest {
	this := PreSignVideoUploadRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *PreSignVideoUploadRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PreSignVideoUploadRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PreSignVideoUploadRequest) SetKey(v string) {
	o.Key = v
}

// GetUploadId returns the UploadId field value
func (o *PreSignVideoUploadRequest) GetUploadId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value
// and a boolean to check if the value has been set.
func (o *PreSignVideoUploadRequest) GetUploadIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadId, true
}

// SetUploadId sets field value
func (o *PreSignVideoUploadRequest) SetUploadId(v string) {
	o.UploadId = v
}

// GetPartNumbers returns the PartNumbers field value
func (o *PreSignVideoUploadRequest) GetPartNumbers() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.PartNumbers
}

// GetPartNumbersOk returns a tuple with the PartNumbers field value
// and a boolean to check if the value has been set.
func (o *PreSignVideoUploadRequest) GetPartNumbersOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PartNumbers, true
}

// SetPartNumbers sets field value
func (o *PreSignVideoUploadRequest) SetPartNumbers(v []int32) {
	o.PartNumbers = v
}

func (o PreSignVideoUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreSignVideoUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["uploadId"] = o.UploadId
	toSerialize["partNumbers"] = o.PartNumbers

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PreSignVideoUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"uploadId",
		"partNumbers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPreSignVideoUploadRequest := _PreSignVideoUploadRequest{}

	err = json.Unmarshal(data, &varPreSignVideoUploadRequest)

	if err != nil {
		return err
	}

	*o = PreSignVideoUploadRequest(varPreSignVideoUploadRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "uploadId")
		delete(additionalProperties, "partNumbers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePreSignVideoUploadRequest struct {
	value *PreSignVideoUploadRequest
	isSet bool
}

func (v NullablePreSignVideoUploadRequest) Get() *PreSignVideoUploadRequest {
	return v.value
}

func (v *NullablePreSignVideoUploadRequest) Set(val *PreSignVideoUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePreSignVideoUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePreSignVideoUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreSignVideoUploadRequest(val *PreSignVideoUploadRequest) *NullablePreSignVideoUploadRequest {
	return &NullablePreSignVideoUploadRequest{value: val, isSet: true}
}

func (v NullablePreSignVideoUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreSignVideoUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


