/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the InitiateImageUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiateImageUploadRequest{}

// InitiateImageUploadRequest struct for InitiateImageUploadRequest
type InitiateImageUploadRequest struct {
	Filename string `json:"filename"`
	AdditionalProperties map[string]interface{}
}

type _InitiateImageUploadRequest InitiateImageUploadRequest

// NewInitiateImageUploadRequest instantiates a new InitiateImageUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiateImageUploadRequest(filename string) *InitiateImageUploadRequest {
	this := InitiateImageUploadRequest{}
	this.Filename = filename
	return &this
}

// NewInitiateImageUploadRequestWithDefaults instantiates a new InitiateImageUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiateImageUploadRequestWithDefaults() *InitiateImageUploadRequest {
	this := InitiateImageUploadRequest{}
	return &this
}

// GetFilename returns the Filename field value
func (o *InitiateImageUploadRequest) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *InitiateImageUploadRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *InitiateImageUploadRequest) SetFilename(v string) {
	o.Filename = v
}

func (o InitiateImageUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiateImageUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filename"] = o.Filename

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InitiateImageUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filename",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInitiateImageUploadRequest := _InitiateImageUploadRequest{}

	err = json.Unmarshal(data, &varInitiateImageUploadRequest)

	if err != nil {
		return err
	}

	*o = InitiateImageUploadRequest(varInitiateImageUploadRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filename")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInitiateImageUploadRequest struct {
	value *InitiateImageUploadRequest
	isSet bool
}

func (v NullableInitiateImageUploadRequest) Get() *InitiateImageUploadRequest {
	return v.value
}

func (v *NullableInitiateImageUploadRequest) Set(val *InitiateImageUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateImageUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateImageUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateImageUploadRequest(val *InitiateImageUploadRequest) *NullableInitiateImageUploadRequest {
	return &NullableInitiateImageUploadRequest{value: val, isSet: true}
}

func (v NullableInitiateImageUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateImageUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


