/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetAppUsage200ResponseMetaLinksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppUsage200ResponseMetaLinksInner{}

// GetAppUsage200ResponseMetaLinksInner struct for GetAppUsage200ResponseMetaLinksInner
type GetAppUsage200ResponseMetaLinksInner struct {
	Url NullableString `json:"url,omitempty"`
	Label *string `json:"label,omitempty"`
	Active *bool `json:"active,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAppUsage200ResponseMetaLinksInner GetAppUsage200ResponseMetaLinksInner

// NewGetAppUsage200ResponseMetaLinksInner instantiates a new GetAppUsage200ResponseMetaLinksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppUsage200ResponseMetaLinksInner() *GetAppUsage200ResponseMetaLinksInner {
	this := GetAppUsage200ResponseMetaLinksInner{}
	return &this
}

// NewGetAppUsage200ResponseMetaLinksInnerWithDefaults instantiates a new GetAppUsage200ResponseMetaLinksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppUsage200ResponseMetaLinksInnerWithDefaults() *GetAppUsage200ResponseMetaLinksInner {
	this := GetAppUsage200ResponseMetaLinksInner{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAppUsage200ResponseMetaLinksInner) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAppUsage200ResponseMetaLinksInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *GetAppUsage200ResponseMetaLinksInner) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *GetAppUsage200ResponseMetaLinksInner) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *GetAppUsage200ResponseMetaLinksInner) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *GetAppUsage200ResponseMetaLinksInner) UnsetUrl() {
	o.Url.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *GetAppUsage200ResponseMetaLinksInner) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppUsage200ResponseMetaLinksInner) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *GetAppUsage200ResponseMetaLinksInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *GetAppUsage200ResponseMetaLinksInner) SetLabel(v string) {
	o.Label = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *GetAppUsage200ResponseMetaLinksInner) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppUsage200ResponseMetaLinksInner) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *GetAppUsage200ResponseMetaLinksInner) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *GetAppUsage200ResponseMetaLinksInner) SetActive(v bool) {
	o.Active = &v
}

func (o GetAppUsage200ResponseMetaLinksInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppUsage200ResponseMetaLinksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAppUsage200ResponseMetaLinksInner) UnmarshalJSON(data []byte) (err error) {
	varGetAppUsage200ResponseMetaLinksInner := _GetAppUsage200ResponseMetaLinksInner{}

	err = json.Unmarshal(data, &varGetAppUsage200ResponseMetaLinksInner)

	if err != nil {
		return err
	}

	*o = GetAppUsage200ResponseMetaLinksInner(varGetAppUsage200ResponseMetaLinksInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "label")
		delete(additionalProperties, "active")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAppUsage200ResponseMetaLinksInner struct {
	value *GetAppUsage200ResponseMetaLinksInner
	isSet bool
}

func (v NullableGetAppUsage200ResponseMetaLinksInner) Get() *GetAppUsage200ResponseMetaLinksInner {
	return v.value
}

func (v *NullableGetAppUsage200ResponseMetaLinksInner) Set(val *GetAppUsage200ResponseMetaLinksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppUsage200ResponseMetaLinksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppUsage200ResponseMetaLinksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppUsage200ResponseMetaLinksInner(val *GetAppUsage200ResponseMetaLinksInner) *NullableGetAppUsage200ResponseMetaLinksInner {
	return &NullableGetAppUsage200ResponseMetaLinksInner{value: val, isSet: true}
}

func (v NullableGetAppUsage200ResponseMetaLinksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppUsage200ResponseMetaLinksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


