/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupHierarchyNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupHierarchyNode{}

// GroupHierarchyNode struct for GroupHierarchyNode
type GroupHierarchyNode struct {
	Id string `json:"id"`
	Name string `json:"name"`
	IsConfigured bool `json:"isConfigured"`
	// Only present for configured groups
	DeviceCount *int32 `json:"deviceCount,omitempty"`
	// Only present for unconfigured groups
	Children []GroupHierarchyNode `json:"children,omitempty"`
	CreatedAt Time `json:"createdAt"`
	UpdatedAt Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _GroupHierarchyNode GroupHierarchyNode

// NewGroupHierarchyNode instantiates a new GroupHierarchyNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupHierarchyNode(id string, name string, isConfigured bool, createdAt Time, updatedAt Time) *GroupHierarchyNode {
	this := GroupHierarchyNode{}
	this.Id = id
	this.Name = name
	this.IsConfigured = isConfigured
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGroupHierarchyNodeWithDefaults instantiates a new GroupHierarchyNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupHierarchyNodeWithDefaults() *GroupHierarchyNode {
	this := GroupHierarchyNode{}
	return &this
}

// GetId returns the Id field value
func (o *GroupHierarchyNode) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupHierarchyNode) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupHierarchyNode) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GroupHierarchyNode) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupHierarchyNode) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupHierarchyNode) SetName(v string) {
	o.Name = v
}

// GetIsConfigured returns the IsConfigured field value
func (o *GroupHierarchyNode) GetIsConfigured() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsConfigured
}

// GetIsConfiguredOk returns a tuple with the IsConfigured field value
// and a boolean to check if the value has been set.
func (o *GroupHierarchyNode) GetIsConfiguredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsConfigured, true
}

// SetIsConfigured sets field value
func (o *GroupHierarchyNode) SetIsConfigured(v bool) {
	o.IsConfigured = v
}

// GetDeviceCount returns the DeviceCount field value if set, zero value otherwise.
func (o *GroupHierarchyNode) GetDeviceCount() int32 {
	if o == nil || IsNil(o.DeviceCount) {
		var ret int32
		return ret
	}
	return *o.DeviceCount
}

// GetDeviceCountOk returns a tuple with the DeviceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupHierarchyNode) GetDeviceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DeviceCount) {
		return nil, false
	}
	return o.DeviceCount, true
}

// HasDeviceCount returns a boolean if a field has been set.
func (o *GroupHierarchyNode) HasDeviceCount() bool {
	if o != nil && !IsNil(o.DeviceCount) {
		return true
	}

	return false
}

// SetDeviceCount gets a reference to the given int32 and assigns it to the DeviceCount field.
func (o *GroupHierarchyNode) SetDeviceCount(v int32) {
	o.DeviceCount = &v
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *GroupHierarchyNode) GetChildren() []GroupHierarchyNode {
	if o == nil || IsNil(o.Children) {
		var ret []GroupHierarchyNode
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupHierarchyNode) GetChildrenOk() ([]GroupHierarchyNode, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *GroupHierarchyNode) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []GroupHierarchyNode and assigns it to the Children field.
func (o *GroupHierarchyNode) SetChildren(v []GroupHierarchyNode) {
	o.Children = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GroupHierarchyNode) GetCreatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GroupHierarchyNode) GetCreatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GroupHierarchyNode) SetCreatedAt(v Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GroupHierarchyNode) GetUpdatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GroupHierarchyNode) GetUpdatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GroupHierarchyNode) SetUpdatedAt(v Time) {
	o.UpdatedAt = v
}

func (o GroupHierarchyNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupHierarchyNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["isConfigured"] = o.IsConfigured
	if !IsNil(o.DeviceCount) {
		toSerialize["deviceCount"] = o.DeviceCount
	}
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupHierarchyNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"isConfigured",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupHierarchyNode := _GroupHierarchyNode{}

	err = json.Unmarshal(data, &varGroupHierarchyNode)

	if err != nil {
		return err
	}

	*o = GroupHierarchyNode(varGroupHierarchyNode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "isConfigured")
		delete(additionalProperties, "deviceCount")
		delete(additionalProperties, "children")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupHierarchyNode struct {
	value *GroupHierarchyNode
	isSet bool
}

func (v NullableGroupHierarchyNode) Get() *GroupHierarchyNode {
	return v.value
}

func (v *NullableGroupHierarchyNode) Set(val *GroupHierarchyNode) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupHierarchyNode) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupHierarchyNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupHierarchyNode(val *GroupHierarchyNode) *NullableGroupHierarchyNode {
	return &NullableGroupHierarchyNode{value: val, isSet: true}
}

func (v NullableGroupHierarchyNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupHierarchyNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


