/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the CreateAppBundle201ResponseAppBuildChecksum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAppBundle201ResponseAppBuildChecksum{}

// CreateAppBundle201ResponseAppBuildChecksum struct for CreateAppBundle201ResponseAppBuildChecksum
type CreateAppBundle201ResponseAppBuildChecksum struct {
	Algorithm *string `json:"algorithm,omitempty"`
	Value *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAppBundle201ResponseAppBuildChecksum CreateAppBundle201ResponseAppBuildChecksum

// NewCreateAppBundle201ResponseAppBuildChecksum instantiates a new CreateAppBundle201ResponseAppBuildChecksum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAppBundle201ResponseAppBuildChecksum() *CreateAppBundle201ResponseAppBuildChecksum {
	this := CreateAppBundle201ResponseAppBuildChecksum{}
	return &this
}

// NewCreateAppBundle201ResponseAppBuildChecksumWithDefaults instantiates a new CreateAppBundle201ResponseAppBuildChecksum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAppBundle201ResponseAppBuildChecksumWithDefaults() *CreateAppBundle201ResponseAppBuildChecksum {
	this := CreateAppBundle201ResponseAppBuildChecksum{}
	return &this
}

// GetAlgorithm returns the Algorithm field value if set, zero value otherwise.
func (o *CreateAppBundle201ResponseAppBuildChecksum) GetAlgorithm() string {
	if o == nil || IsNil(o.Algorithm) {
		var ret string
		return ret
	}
	return *o.Algorithm
}

// GetAlgorithmOk returns a tuple with the Algorithm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppBundle201ResponseAppBuildChecksum) GetAlgorithmOk() (*string, bool) {
	if o == nil || IsNil(o.Algorithm) {
		return nil, false
	}
	return o.Algorithm, true
}

// HasAlgorithm returns a boolean if a field has been set.
func (o *CreateAppBundle201ResponseAppBuildChecksum) HasAlgorithm() bool {
	if o != nil && !IsNil(o.Algorithm) {
		return true
	}

	return false
}

// SetAlgorithm gets a reference to the given string and assigns it to the Algorithm field.
func (o *CreateAppBundle201ResponseAppBuildChecksum) SetAlgorithm(v string) {
	o.Algorithm = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CreateAppBundle201ResponseAppBuildChecksum) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAppBundle201ResponseAppBuildChecksum) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CreateAppBundle201ResponseAppBuildChecksum) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CreateAppBundle201ResponseAppBuildChecksum) SetValue(v string) {
	o.Value = &v
}

func (o CreateAppBundle201ResponseAppBuildChecksum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAppBundle201ResponseAppBuildChecksum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Algorithm) {
		toSerialize["algorithm"] = o.Algorithm
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAppBundle201ResponseAppBuildChecksum) UnmarshalJSON(data []byte) (err error) {
	varCreateAppBundle201ResponseAppBuildChecksum := _CreateAppBundle201ResponseAppBuildChecksum{}

	err = json.Unmarshal(data, &varCreateAppBundle201ResponseAppBuildChecksum)

	if err != nil {
		return err
	}

	*o = CreateAppBundle201ResponseAppBuildChecksum(varCreateAppBundle201ResponseAppBuildChecksum)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "algorithm")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAppBundle201ResponseAppBuildChecksum struct {
	value *CreateAppBundle201ResponseAppBuildChecksum
	isSet bool
}

func (v NullableCreateAppBundle201ResponseAppBuildChecksum) Get() *CreateAppBundle201ResponseAppBuildChecksum {
	return v.value
}

func (v *NullableCreateAppBundle201ResponseAppBuildChecksum) Set(val *CreateAppBundle201ResponseAppBuildChecksum) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAppBundle201ResponseAppBuildChecksum) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAppBundle201ResponseAppBuildChecksum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAppBundle201ResponseAppBuildChecksum(val *CreateAppBundle201ResponseAppBuildChecksum) *NullableCreateAppBundle201ResponseAppBuildChecksum {
	return &NullableCreateAppBundle201ResponseAppBuildChecksum{value: val, isSet: true}
}

func (v NullableCreateAppBundle201ResponseAppBuildChecksum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAppBundle201ResponseAppBuildChecksum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


