/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetAppSessions200ResponseDataInnerDevice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppSessions200ResponseDataInnerDevice{}

// GetAppSessions200ResponseDataInnerDevice Details of the device used for the app session.
type GetAppSessions200ResponseDataInnerDevice struct {
	// The unique identifier of the device.
	Id *string `json:"id,omitempty"`
	// The name of the device.
	Name *string `json:"name,omitempty"`
	// The serial number of the device.
	Serial *string `json:"serial,omitempty"`
	Group NullableGetAppSessions200ResponseDataInnerDeviceGroup `json:"group,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAppSessions200ResponseDataInnerDevice GetAppSessions200ResponseDataInnerDevice

// NewGetAppSessions200ResponseDataInnerDevice instantiates a new GetAppSessions200ResponseDataInnerDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppSessions200ResponseDataInnerDevice() *GetAppSessions200ResponseDataInnerDevice {
	this := GetAppSessions200ResponseDataInnerDevice{}
	return &this
}

// NewGetAppSessions200ResponseDataInnerDeviceWithDefaults instantiates a new GetAppSessions200ResponseDataInnerDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppSessions200ResponseDataInnerDeviceWithDefaults() *GetAppSessions200ResponseDataInnerDevice {
	this := GetAppSessions200ResponseDataInnerDevice{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInnerDevice) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInnerDevice) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInnerDevice) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetAppSessions200ResponseDataInnerDevice) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInnerDevice) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInnerDevice) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInnerDevice) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAppSessions200ResponseDataInnerDevice) SetName(v string) {
	o.Name = &v
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInnerDevice) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInnerDevice) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInnerDevice) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *GetAppSessions200ResponseDataInnerDevice) SetSerial(v string) {
	o.Serial = &v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAppSessions200ResponseDataInnerDevice) GetGroup() GetAppSessions200ResponseDataInnerDeviceGroup {
	if o == nil || IsNil(o.Group.Get()) {
		var ret GetAppSessions200ResponseDataInnerDeviceGroup
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAppSessions200ResponseDataInnerDevice) GetGroupOk() (*GetAppSessions200ResponseDataInnerDeviceGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInnerDevice) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableGetAppSessions200ResponseDataInnerDeviceGroup and assigns it to the Group field.
func (o *GetAppSessions200ResponseDataInnerDevice) SetGroup(v GetAppSessions200ResponseDataInnerDeviceGroup) {
	o.Group.Set(&v)
}
// SetGroupNil sets the value for Group to be an explicit nil
func (o *GetAppSessions200ResponseDataInnerDevice) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *GetAppSessions200ResponseDataInnerDevice) UnsetGroup() {
	o.Group.Unset()
}

func (o GetAppSessions200ResponseDataInnerDevice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppSessions200ResponseDataInnerDevice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAppSessions200ResponseDataInnerDevice) UnmarshalJSON(data []byte) (err error) {
	varGetAppSessions200ResponseDataInnerDevice := _GetAppSessions200ResponseDataInnerDevice{}

	err = json.Unmarshal(data, &varGetAppSessions200ResponseDataInnerDevice)

	if err != nil {
		return err
	}

	*o = GetAppSessions200ResponseDataInnerDevice(varGetAppSessions200ResponseDataInnerDevice)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "serial")
		delete(additionalProperties, "group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAppSessions200ResponseDataInnerDevice struct {
	value *GetAppSessions200ResponseDataInnerDevice
	isSet bool
}

func (v NullableGetAppSessions200ResponseDataInnerDevice) Get() *GetAppSessions200ResponseDataInnerDevice {
	return v.value
}

func (v *NullableGetAppSessions200ResponseDataInnerDevice) Set(val *GetAppSessions200ResponseDataInnerDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppSessions200ResponseDataInnerDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppSessions200ResponseDataInnerDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppSessions200ResponseDataInnerDevice(val *GetAppSessions200ResponseDataInnerDevice) *NullableGetAppSessions200ResponseDataInnerDevice {
	return &NullableGetAppSessions200ResponseDataInnerDevice{value: val, isSet: true}
}

func (v NullableGetAppSessions200ResponseDataInnerDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppSessions200ResponseDataInnerDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


