/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetCustom3DEnvironments200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustom3DEnvironments200ResponseDataInner{}

// GetCustom3DEnvironments200ResponseDataInner struct for GetCustom3DEnvironments200ResponseDataInner
type GetCustom3DEnvironments200ResponseDataInner struct {
	Id string `json:"id"`
	// The filename of the 3D environment file (must be .glb format)
	ObjectName string `json:"objectName"`
	// The size of the 3D environment file in bytes
	SizeBytes NullableInt32 `json:"sizeBytes,omitempty"`
	// The current status of the 3D environment
	Status string `json:"status"`
	// Download URL for the 3D environment (only present when status is available)
	DownloadUrl NullableString `json:"downloadUrl,omitempty"`
	CreatedAt Time `json:"createdAt"`
	UpdatedAt Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _GetCustom3DEnvironments200ResponseDataInner GetCustom3DEnvironments200ResponseDataInner

// NewGetCustom3DEnvironments200ResponseDataInner instantiates a new GetCustom3DEnvironments200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustom3DEnvironments200ResponseDataInner(id string, objectName string, status string, createdAt Time, updatedAt Time) *GetCustom3DEnvironments200ResponseDataInner {
	this := GetCustom3DEnvironments200ResponseDataInner{}
	this.Id = id
	this.ObjectName = objectName
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetCustom3DEnvironments200ResponseDataInnerWithDefaults instantiates a new GetCustom3DEnvironments200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustom3DEnvironments200ResponseDataInnerWithDefaults() *GetCustom3DEnvironments200ResponseDataInner {
	this := GetCustom3DEnvironments200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetCustom3DEnvironments200ResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetCustom3DEnvironments200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetCustom3DEnvironments200ResponseDataInner) SetId(v string) {
	o.Id = v
}

// GetObjectName returns the ObjectName field value
func (o *GetCustom3DEnvironments200ResponseDataInner) GetObjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectName
}

// GetObjectNameOk returns a tuple with the ObjectName field value
// and a boolean to check if the value has been set.
func (o *GetCustom3DEnvironments200ResponseDataInner) GetObjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectName, true
}

// SetObjectName sets field value
func (o *GetCustom3DEnvironments200ResponseDataInner) SetObjectName(v string) {
	o.ObjectName = v
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustom3DEnvironments200ResponseDataInner) GetSizeBytes() int32 {
	if o == nil || IsNil(o.SizeBytes.Get()) {
		var ret int32
		return ret
	}
	return *o.SizeBytes.Get()
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustom3DEnvironments200ResponseDataInner) GetSizeBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SizeBytes.Get(), o.SizeBytes.IsSet()
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *GetCustom3DEnvironments200ResponseDataInner) HasSizeBytes() bool {
	if o != nil && o.SizeBytes.IsSet() {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given NullableInt32 and assigns it to the SizeBytes field.
func (o *GetCustom3DEnvironments200ResponseDataInner) SetSizeBytes(v int32) {
	o.SizeBytes.Set(&v)
}
// SetSizeBytesNil sets the value for SizeBytes to be an explicit nil
func (o *GetCustom3DEnvironments200ResponseDataInner) SetSizeBytesNil() {
	o.SizeBytes.Set(nil)
}

// UnsetSizeBytes ensures that no value is present for SizeBytes, not even an explicit nil
func (o *GetCustom3DEnvironments200ResponseDataInner) UnsetSizeBytes() {
	o.SizeBytes.Unset()
}

// GetStatus returns the Status field value
func (o *GetCustom3DEnvironments200ResponseDataInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetCustom3DEnvironments200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetCustom3DEnvironments200ResponseDataInner) SetStatus(v string) {
	o.Status = v
}

// GetDownloadUrl returns the DownloadUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCustom3DEnvironments200ResponseDataInner) GetDownloadUrl() string {
	if o == nil || IsNil(o.DownloadUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DownloadUrl.Get()
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCustom3DEnvironments200ResponseDataInner) GetDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DownloadUrl.Get(), o.DownloadUrl.IsSet()
}

// HasDownloadUrl returns a boolean if a field has been set.
func (o *GetCustom3DEnvironments200ResponseDataInner) HasDownloadUrl() bool {
	if o != nil && o.DownloadUrl.IsSet() {
		return true
	}

	return false
}

// SetDownloadUrl gets a reference to the given NullableString and assigns it to the DownloadUrl field.
func (o *GetCustom3DEnvironments200ResponseDataInner) SetDownloadUrl(v string) {
	o.DownloadUrl.Set(&v)
}
// SetDownloadUrlNil sets the value for DownloadUrl to be an explicit nil
func (o *GetCustom3DEnvironments200ResponseDataInner) SetDownloadUrlNil() {
	o.DownloadUrl.Set(nil)
}

// UnsetDownloadUrl ensures that no value is present for DownloadUrl, not even an explicit nil
func (o *GetCustom3DEnvironments200ResponseDataInner) UnsetDownloadUrl() {
	o.DownloadUrl.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetCustom3DEnvironments200ResponseDataInner) GetCreatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetCustom3DEnvironments200ResponseDataInner) GetCreatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetCustom3DEnvironments200ResponseDataInner) SetCreatedAt(v Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetCustom3DEnvironments200ResponseDataInner) GetUpdatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetCustom3DEnvironments200ResponseDataInner) GetUpdatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetCustom3DEnvironments200ResponseDataInner) SetUpdatedAt(v Time) {
	o.UpdatedAt = v
}

func (o GetCustom3DEnvironments200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustom3DEnvironments200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["objectName"] = o.ObjectName
	if o.SizeBytes.IsSet() {
		toSerialize["sizeBytes"] = o.SizeBytes.Get()
	}
	toSerialize["status"] = o.Status
	if o.DownloadUrl.IsSet() {
		toSerialize["downloadUrl"] = o.DownloadUrl.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCustom3DEnvironments200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"objectName",
		"status",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCustom3DEnvironments200ResponseDataInner := _GetCustom3DEnvironments200ResponseDataInner{}

	err = json.Unmarshal(data, &varGetCustom3DEnvironments200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetCustom3DEnvironments200ResponseDataInner(varGetCustom3DEnvironments200ResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "objectName")
		delete(additionalProperties, "sizeBytes")
		delete(additionalProperties, "status")
		delete(additionalProperties, "downloadUrl")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCustom3DEnvironments200ResponseDataInner struct {
	value *GetCustom3DEnvironments200ResponseDataInner
	isSet bool
}

func (v NullableGetCustom3DEnvironments200ResponseDataInner) Get() *GetCustom3DEnvironments200ResponseDataInner {
	return v.value
}

func (v *NullableGetCustom3DEnvironments200ResponseDataInner) Set(val *GetCustom3DEnvironments200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustom3DEnvironments200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustom3DEnvironments200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustom3DEnvironments200ResponseDataInner(val *GetCustom3DEnvironments200ResponseDataInner) *NullableGetCustom3DEnvironments200ResponseDataInner {
	return &NullableGetCustom3DEnvironments200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetCustom3DEnvironments200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustom3DEnvironments200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


