/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetVideos200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVideos200ResponseMeta{}

// GetVideos200ResponseMeta struct for GetVideos200ResponseMeta
type GetVideos200ResponseMeta struct {
	CurrentPage *int32 `json:"current_page,omitempty"`
	From NullableInt32 `json:"from,omitempty"`
	LastPage *int32 `json:"last_page,omitempty"`
	Links []GetVideos200ResponseMetaLinksInner `json:"links,omitempty"`
	Path *string `json:"path,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	To NullableInt32 `json:"to,omitempty"`
	Total *int32 `json:"total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetVideos200ResponseMeta GetVideos200ResponseMeta

// NewGetVideos200ResponseMeta instantiates a new GetVideos200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVideos200ResponseMeta() *GetVideos200ResponseMeta {
	this := GetVideos200ResponseMeta{}
	return &this
}

// NewGetVideos200ResponseMetaWithDefaults instantiates a new GetVideos200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVideos200ResponseMetaWithDefaults() *GetVideos200ResponseMeta {
	this := GetVideos200ResponseMeta{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *GetVideos200ResponseMeta) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseMeta) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *GetVideos200ResponseMeta) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetFrom returns the From field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideos200ResponseMeta) GetFrom() int32 {
	if o == nil || IsNil(o.From.Get()) {
		var ret int32
		return ret
	}
	return *o.From.Get()
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideos200ResponseMeta) GetFromOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.From.Get(), o.From.IsSet()
}

// HasFrom returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasFrom() bool {
	if o != nil && o.From.IsSet() {
		return true
	}

	return false
}

// SetFrom gets a reference to the given NullableInt32 and assigns it to the From field.
func (o *GetVideos200ResponseMeta) SetFrom(v int32) {
	o.From.Set(&v)
}
// SetFromNil sets the value for From to be an explicit nil
func (o *GetVideos200ResponseMeta) SetFromNil() {
	o.From.Set(nil)
}

// UnsetFrom ensures that no value is present for From, not even an explicit nil
func (o *GetVideos200ResponseMeta) UnsetFrom() {
	o.From.Unset()
}

// GetLastPage returns the LastPage field value if set, zero value otherwise.
func (o *GetVideos200ResponseMeta) GetLastPage() int32 {
	if o == nil || IsNil(o.LastPage) {
		var ret int32
		return ret
	}
	return *o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseMeta) GetLastPageOk() (*int32, bool) {
	if o == nil || IsNil(o.LastPage) {
		return nil, false
	}
	return o.LastPage, true
}

// HasLastPage returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasLastPage() bool {
	if o != nil && !IsNil(o.LastPage) {
		return true
	}

	return false
}

// SetLastPage gets a reference to the given int32 and assigns it to the LastPage field.
func (o *GetVideos200ResponseMeta) SetLastPage(v int32) {
	o.LastPage = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetVideos200ResponseMeta) GetLinks() []GetVideos200ResponseMetaLinksInner {
	if o == nil || IsNil(o.Links) {
		var ret []GetVideos200ResponseMetaLinksInner
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseMeta) GetLinksOk() ([]GetVideos200ResponseMetaLinksInner, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []GetVideos200ResponseMetaLinksInner and assigns it to the Links field.
func (o *GetVideos200ResponseMeta) SetLinks(v []GetVideos200ResponseMetaLinksInner) {
	o.Links = v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *GetVideos200ResponseMeta) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseMeta) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *GetVideos200ResponseMeta) SetPath(v string) {
	o.Path = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *GetVideos200ResponseMeta) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseMeta) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *GetVideos200ResponseMeta) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetTo returns the To field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetVideos200ResponseMeta) GetTo() int32 {
	if o == nil || IsNil(o.To.Get()) {
		var ret int32
		return ret
	}
	return *o.To.Get()
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetVideos200ResponseMeta) GetToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.To.Get(), o.To.IsSet()
}

// HasTo returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasTo() bool {
	if o != nil && o.To.IsSet() {
		return true
	}

	return false
}

// SetTo gets a reference to the given NullableInt32 and assigns it to the To field.
func (o *GetVideos200ResponseMeta) SetTo(v int32) {
	o.To.Set(&v)
}
// SetToNil sets the value for To to be an explicit nil
func (o *GetVideos200ResponseMeta) SetToNil() {
	o.To.Set(nil)
}

// UnsetTo ensures that no value is present for To, not even an explicit nil
func (o *GetVideos200ResponseMeta) UnsetTo() {
	o.To.Unset()
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetVideos200ResponseMeta) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideos200ResponseMeta) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetVideos200ResponseMeta) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetVideos200ResponseMeta) SetTotal(v int32) {
	o.Total = &v
}

func (o GetVideos200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVideos200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if o.From.IsSet() {
		toSerialize["from"] = o.From.Get()
	}
	if !IsNil(o.LastPage) {
		toSerialize["last_page"] = o.LastPage
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if o.To.IsSet() {
		toSerialize["to"] = o.To.Get()
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetVideos200ResponseMeta) UnmarshalJSON(data []byte) (err error) {
	varGetVideos200ResponseMeta := _GetVideos200ResponseMeta{}

	err = json.Unmarshal(data, &varGetVideos200ResponseMeta)

	if err != nil {
		return err
	}

	*o = GetVideos200ResponseMeta(varGetVideos200ResponseMeta)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "current_page")
		delete(additionalProperties, "from")
		delete(additionalProperties, "last_page")
		delete(additionalProperties, "links")
		delete(additionalProperties, "path")
		delete(additionalProperties, "per_page")
		delete(additionalProperties, "to")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetVideos200ResponseMeta struct {
	value *GetVideos200ResponseMeta
	isSet bool
}

func (v NullableGetVideos200ResponseMeta) Get() *GetVideos200ResponseMeta {
	return v.value
}

func (v *NullableGetVideos200ResponseMeta) Set(val *GetVideos200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVideos200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVideos200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVideos200ResponseMeta(val *GetVideos200ResponseMeta) *NullableGetVideos200ResponseMeta {
	return &NullableGetVideos200ResponseMeta{value: val, isSet: true}
}

func (v NullableGetVideos200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVideos200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


