/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetAppSessions200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppSessions200ResponseDataInner{}

// GetAppSessions200ResponseDataInner An individual app session representing usage of an app on a device.
type GetAppSessions200ResponseDataInner struct {
	// The unique identifier of the app session.
	Id *string `json:"id,omitempty"`
	// The total duration of the app session in seconds.
	TotalDuration *int32 `json:"totalDuration,omitempty"`
	// The idle duration of the app session in seconds.
	IdleDuration *int32 `json:"idleDuration,omitempty"`
	// The active duration of the app session in seconds.
	ActiveDuration *int32 `json:"activeDuration,omitempty"`
	StartedAt NullableTime `json:"startedAt,omitempty"`
	EndedAt NullableTime `json:"endedAt,omitempty"`
	Device *GetAppSessions200ResponseDataInnerDevice `json:"device,omitempty"`
	App *GetAppSessions200ResponseDataInnerApp `json:"app,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAppSessions200ResponseDataInner GetAppSessions200ResponseDataInner

// NewGetAppSessions200ResponseDataInner instantiates a new GetAppSessions200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppSessions200ResponseDataInner() *GetAppSessions200ResponseDataInner {
	this := GetAppSessions200ResponseDataInner{}
	return &this
}

// NewGetAppSessions200ResponseDataInnerWithDefaults instantiates a new GetAppSessions200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppSessions200ResponseDataInnerWithDefaults() *GetAppSessions200ResponseDataInner {
	this := GetAppSessions200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetAppSessions200ResponseDataInner) SetId(v string) {
	o.Id = &v
}

// GetTotalDuration returns the TotalDuration field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInner) GetTotalDuration() int32 {
	if o == nil || IsNil(o.TotalDuration) {
		var ret int32
		return ret
	}
	return *o.TotalDuration
}

// GetTotalDurationOk returns a tuple with the TotalDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInner) GetTotalDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalDuration) {
		return nil, false
	}
	return o.TotalDuration, true
}

// HasTotalDuration returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasTotalDuration() bool {
	if o != nil && !IsNil(o.TotalDuration) {
		return true
	}

	return false
}

// SetTotalDuration gets a reference to the given int32 and assigns it to the TotalDuration field.
func (o *GetAppSessions200ResponseDataInner) SetTotalDuration(v int32) {
	o.TotalDuration = &v
}

// GetIdleDuration returns the IdleDuration field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInner) GetIdleDuration() int32 {
	if o == nil || IsNil(o.IdleDuration) {
		var ret int32
		return ret
	}
	return *o.IdleDuration
}

// GetIdleDurationOk returns a tuple with the IdleDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInner) GetIdleDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.IdleDuration) {
		return nil, false
	}
	return o.IdleDuration, true
}

// HasIdleDuration returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasIdleDuration() bool {
	if o != nil && !IsNil(o.IdleDuration) {
		return true
	}

	return false
}

// SetIdleDuration gets a reference to the given int32 and assigns it to the IdleDuration field.
func (o *GetAppSessions200ResponseDataInner) SetIdleDuration(v int32) {
	o.IdleDuration = &v
}

// GetActiveDuration returns the ActiveDuration field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInner) GetActiveDuration() int32 {
	if o == nil || IsNil(o.ActiveDuration) {
		var ret int32
		return ret
	}
	return *o.ActiveDuration
}

// GetActiveDurationOk returns a tuple with the ActiveDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInner) GetActiveDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveDuration) {
		return nil, false
	}
	return o.ActiveDuration, true
}

// HasActiveDuration returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasActiveDuration() bool {
	if o != nil && !IsNil(o.ActiveDuration) {
		return true
	}

	return false
}

// SetActiveDuration gets a reference to the given int32 and assigns it to the ActiveDuration field.
func (o *GetAppSessions200ResponseDataInner) SetActiveDuration(v int32) {
	o.ActiveDuration = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAppSessions200ResponseDataInner) GetStartedAt() Time {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret Time
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAppSessions200ResponseDataInner) GetStartedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableTime and assigns it to the StartedAt field.
func (o *GetAppSessions200ResponseDataInner) SetStartedAt(v Time) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *GetAppSessions200ResponseDataInner) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *GetAppSessions200ResponseDataInner) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAppSessions200ResponseDataInner) GetEndedAt() Time {
	if o == nil || IsNil(o.EndedAt.Get()) {
		var ret Time
		return ret
	}
	return *o.EndedAt.Get()
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAppSessions200ResponseDataInner) GetEndedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndedAt.Get(), o.EndedAt.IsSet()
}

// HasEndedAt returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasEndedAt() bool {
	if o != nil && o.EndedAt.IsSet() {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given NullableTime and assigns it to the EndedAt field.
func (o *GetAppSessions200ResponseDataInner) SetEndedAt(v Time) {
	o.EndedAt.Set(&v)
}
// SetEndedAtNil sets the value for EndedAt to be an explicit nil
func (o *GetAppSessions200ResponseDataInner) SetEndedAtNil() {
	o.EndedAt.Set(nil)
}

// UnsetEndedAt ensures that no value is present for EndedAt, not even an explicit nil
func (o *GetAppSessions200ResponseDataInner) UnsetEndedAt() {
	o.EndedAt.Unset()
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInner) GetDevice() GetAppSessions200ResponseDataInnerDevice {
	if o == nil || IsNil(o.Device) {
		var ret GetAppSessions200ResponseDataInnerDevice
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInner) GetDeviceOk() (*GetAppSessions200ResponseDataInnerDevice, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given GetAppSessions200ResponseDataInnerDevice and assigns it to the Device field.
func (o *GetAppSessions200ResponseDataInner) SetDevice(v GetAppSessions200ResponseDataInnerDevice) {
	o.Device = &v
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *GetAppSessions200ResponseDataInner) GetApp() GetAppSessions200ResponseDataInnerApp {
	if o == nil || IsNil(o.App) {
		var ret GetAppSessions200ResponseDataInnerApp
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppSessions200ResponseDataInner) GetAppOk() (*GetAppSessions200ResponseDataInnerApp, bool) {
	if o == nil || IsNil(o.App) {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *GetAppSessions200ResponseDataInner) HasApp() bool {
	if o != nil && !IsNil(o.App) {
		return true
	}

	return false
}

// SetApp gets a reference to the given GetAppSessions200ResponseDataInnerApp and assigns it to the App field.
func (o *GetAppSessions200ResponseDataInner) SetApp(v GetAppSessions200ResponseDataInnerApp) {
	o.App = &v
}

func (o GetAppSessions200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppSessions200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.TotalDuration) {
		toSerialize["totalDuration"] = o.TotalDuration
	}
	if !IsNil(o.IdleDuration) {
		toSerialize["idleDuration"] = o.IdleDuration
	}
	if !IsNil(o.ActiveDuration) {
		toSerialize["activeDuration"] = o.ActiveDuration
	}
	if o.StartedAt.IsSet() {
		toSerialize["startedAt"] = o.StartedAt.Get()
	}
	if o.EndedAt.IsSet() {
		toSerialize["endedAt"] = o.EndedAt.Get()
	}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.App) {
		toSerialize["app"] = o.App
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAppSessions200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	varGetAppSessions200ResponseDataInner := _GetAppSessions200ResponseDataInner{}

	err = json.Unmarshal(data, &varGetAppSessions200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetAppSessions200ResponseDataInner(varGetAppSessions200ResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "totalDuration")
		delete(additionalProperties, "idleDuration")
		delete(additionalProperties, "activeDuration")
		delete(additionalProperties, "startedAt")
		delete(additionalProperties, "endedAt")
		delete(additionalProperties, "device")
		delete(additionalProperties, "app")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAppSessions200ResponseDataInner struct {
	value *GetAppSessions200ResponseDataInner
	isSet bool
}

func (v NullableGetAppSessions200ResponseDataInner) Get() *GetAppSessions200ResponseDataInner {
	return v.value
}

func (v *NullableGetAppSessions200ResponseDataInner) Set(val *GetAppSessions200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppSessions200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppSessions200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppSessions200ResponseDataInner(val *GetAppSessions200ResponseDataInner) *NullableGetAppSessions200ResponseDataInner {
	return &NullableGetAppSessions200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetAppSessions200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppSessions200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


