/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetAppBundleFiles200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppBundleFiles200ResponseDataInner{}

// GetAppBundleFiles200ResponseDataInner struct for GetAppBundleFiles200ResponseDataInner
type GetAppBundleFiles200ResponseDataInner struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Location string `json:"location"`
	BundlePaths []string `json:"bundlePaths"`
	SizeBytes int32 `json:"sizeBytes"`
	Checksum CreateAppBundle201ResponseAppBuildChecksum `json:"checksum"`
	CreatedAt Time `json:"createdAt"`
	UpdatedAt Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _GetAppBundleFiles200ResponseDataInner GetAppBundleFiles200ResponseDataInner

// NewGetAppBundleFiles200ResponseDataInner instantiates a new GetAppBundleFiles200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppBundleFiles200ResponseDataInner(id string, name string, location string, bundlePaths []string, sizeBytes int32, checksum CreateAppBundle201ResponseAppBuildChecksum, createdAt Time, updatedAt Time) *GetAppBundleFiles200ResponseDataInner {
	this := GetAppBundleFiles200ResponseDataInner{}
	this.Id = id
	this.Name = name
	this.Location = location
	this.BundlePaths = bundlePaths
	this.SizeBytes = sizeBytes
	this.Checksum = checksum
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetAppBundleFiles200ResponseDataInnerWithDefaults instantiates a new GetAppBundleFiles200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppBundleFiles200ResponseDataInnerWithDefaults() *GetAppBundleFiles200ResponseDataInner {
	this := GetAppBundleFiles200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetAppBundleFiles200ResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetAppBundleFiles200ResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetName(v string) {
	o.Name = v
}

// GetLocation returns the Location field value
func (o *GetAppBundleFiles200ResponseDataInner) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetLocation(v string) {
	o.Location = v
}

// GetBundlePaths returns the BundlePaths field value
func (o *GetAppBundleFiles200ResponseDataInner) GetBundlePaths() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BundlePaths
}

// GetBundlePathsOk returns a tuple with the BundlePaths field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetBundlePathsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BundlePaths, true
}

// SetBundlePaths sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetBundlePaths(v []string) {
	o.BundlePaths = v
}

// GetSizeBytes returns the SizeBytes field value
func (o *GetAppBundleFiles200ResponseDataInner) GetSizeBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetSizeBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SizeBytes, true
}

// SetSizeBytes sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetSizeBytes(v int32) {
	o.SizeBytes = v
}

// GetChecksum returns the Checksum field value
func (o *GetAppBundleFiles200ResponseDataInner) GetChecksum() CreateAppBundle201ResponseAppBuildChecksum {
	if o == nil {
		var ret CreateAppBundle201ResponseAppBuildChecksum
		return ret
	}

	return o.Checksum
}

// GetChecksumOk returns a tuple with the Checksum field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetChecksumOk() (*CreateAppBundle201ResponseAppBuildChecksum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Checksum, true
}

// SetChecksum sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetChecksum(v CreateAppBundle201ResponseAppBuildChecksum) {
	o.Checksum = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetAppBundleFiles200ResponseDataInner) GetCreatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetCreatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetCreatedAt(v Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetAppBundleFiles200ResponseDataInner) GetUpdatedAt() Time {
	if o == nil {
		var ret Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetAppBundleFiles200ResponseDataInner) GetUpdatedAtOk() (*Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetAppBundleFiles200ResponseDataInner) SetUpdatedAt(v Time) {
	o.UpdatedAt = v
}

func (o GetAppBundleFiles200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppBundleFiles200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["location"] = o.Location
	toSerialize["bundlePaths"] = o.BundlePaths
	toSerialize["sizeBytes"] = o.SizeBytes
	toSerialize["checksum"] = o.Checksum
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAppBundleFiles200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"location",
		"bundlePaths",
		"sizeBytes",
		"checksum",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAppBundleFiles200ResponseDataInner := _GetAppBundleFiles200ResponseDataInner{}

	err = json.Unmarshal(data, &varGetAppBundleFiles200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetAppBundleFiles200ResponseDataInner(varGetAppBundleFiles200ResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "location")
		delete(additionalProperties, "bundlePaths")
		delete(additionalProperties, "sizeBytes")
		delete(additionalProperties, "checksum")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAppBundleFiles200ResponseDataInner struct {
	value *GetAppBundleFiles200ResponseDataInner
	isSet bool
}

func (v NullableGetAppBundleFiles200ResponseDataInner) Get() *GetAppBundleFiles200ResponseDataInner {
	return v.value
}

func (v *NullableGetAppBundleFiles200ResponseDataInner) Set(val *GetAppBundleFiles200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppBundleFiles200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppBundleFiles200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppBundleFiles200ResponseDataInner(val *GetAppBundleFiles200ResponseDataInner) *NullableGetAppBundleFiles200ResponseDataInner {
	return &NullableGetAppBundleFiles200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetAppBundleFiles200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppBundleFiles200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


