/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateUserInviteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUserInviteRequest{}

// CreateUserInviteRequest struct for CreateUserInviteRequest
type CreateUserInviteRequest struct {
	// The email address of the user to invite.
	Email string `json:"email"`
	// Should the user be required to authenticate using the organization's configured IdP?
	IsSsoEnforced *bool `json:"isSsoEnforced,omitempty"`
	// The default role assigned to the user. Can be an organization role or a group role.
	DefaultRoleId string `json:"defaultRoleId"`
	// Optional group roles to assign to the user upon invitation.
	GroupRoles []CreateUserRequestGroupRolesInner `json:"groupRoles,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateUserInviteRequest CreateUserInviteRequest

// NewCreateUserInviteRequest instantiates a new CreateUserInviteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUserInviteRequest(email string, defaultRoleId string) *CreateUserInviteRequest {
	this := CreateUserInviteRequest{}
	this.Email = email
	this.DefaultRoleId = defaultRoleId
	return &this
}

// NewCreateUserInviteRequestWithDefaults instantiates a new CreateUserInviteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUserInviteRequestWithDefaults() *CreateUserInviteRequest {
	this := CreateUserInviteRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *CreateUserInviteRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreateUserInviteRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreateUserInviteRequest) SetEmail(v string) {
	o.Email = v
}

// GetIsSsoEnforced returns the IsSsoEnforced field value if set, zero value otherwise.
func (o *CreateUserInviteRequest) GetIsSsoEnforced() bool {
	if o == nil || IsNil(o.IsSsoEnforced) {
		var ret bool
		return ret
	}
	return *o.IsSsoEnforced
}

// GetIsSsoEnforcedOk returns a tuple with the IsSsoEnforced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserInviteRequest) GetIsSsoEnforcedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSsoEnforced) {
		return nil, false
	}
	return o.IsSsoEnforced, true
}

// HasIsSsoEnforced returns a boolean if a field has been set.
func (o *CreateUserInviteRequest) HasIsSsoEnforced() bool {
	if o != nil && !IsNil(o.IsSsoEnforced) {
		return true
	}

	return false
}

// SetIsSsoEnforced gets a reference to the given bool and assigns it to the IsSsoEnforced field.
func (o *CreateUserInviteRequest) SetIsSsoEnforced(v bool) {
	o.IsSsoEnforced = &v
}

// GetDefaultRoleId returns the DefaultRoleId field value
func (o *CreateUserInviteRequest) GetDefaultRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultRoleId
}

// GetDefaultRoleIdOk returns a tuple with the DefaultRoleId field value
// and a boolean to check if the value has been set.
func (o *CreateUserInviteRequest) GetDefaultRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultRoleId, true
}

// SetDefaultRoleId sets field value
func (o *CreateUserInviteRequest) SetDefaultRoleId(v string) {
	o.DefaultRoleId = v
}

// GetGroupRoles returns the GroupRoles field value if set, zero value otherwise.
func (o *CreateUserInviteRequest) GetGroupRoles() []CreateUserRequestGroupRolesInner {
	if o == nil || IsNil(o.GroupRoles) {
		var ret []CreateUserRequestGroupRolesInner
		return ret
	}
	return o.GroupRoles
}

// GetGroupRolesOk returns a tuple with the GroupRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUserInviteRequest) GetGroupRolesOk() ([]CreateUserRequestGroupRolesInner, bool) {
	if o == nil || IsNil(o.GroupRoles) {
		return nil, false
	}
	return o.GroupRoles, true
}

// HasGroupRoles returns a boolean if a field has been set.
func (o *CreateUserInviteRequest) HasGroupRoles() bool {
	if o != nil && !IsNil(o.GroupRoles) {
		return true
	}

	return false
}

// SetGroupRoles gets a reference to the given []CreateUserRequestGroupRolesInner and assigns it to the GroupRoles field.
func (o *CreateUserInviteRequest) SetGroupRoles(v []CreateUserRequestGroupRolesInner) {
	o.GroupRoles = v
}

func (o CreateUserInviteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUserInviteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.IsSsoEnforced) {
		toSerialize["isSsoEnforced"] = o.IsSsoEnforced
	}
	toSerialize["defaultRoleId"] = o.DefaultRoleId
	if !IsNil(o.GroupRoles) {
		toSerialize["groupRoles"] = o.GroupRoles
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateUserInviteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"defaultRoleId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUserInviteRequest := _CreateUserInviteRequest{}

	err = json.Unmarshal(data, &varCreateUserInviteRequest)

	if err != nil {
		return err
	}

	*o = CreateUserInviteRequest(varCreateUserInviteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "email")
		delete(additionalProperties, "isSsoEnforced")
		delete(additionalProperties, "defaultRoleId")
		delete(additionalProperties, "groupRoles")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateUserInviteRequest struct {
	value *CreateUserInviteRequest
	isSet bool
}

func (v NullableCreateUserInviteRequest) Get() *CreateUserInviteRequest {
	return v.value
}

func (v *NullableCreateUserInviteRequest) Set(val *CreateUserInviteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUserInviteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUserInviteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUserInviteRequest(val *CreateUserInviteRequest) *NullableCreateUserInviteRequest {
	return &NullableCreateUserInviteRequest{value: val, isSet: true}
}

func (v NullableCreateUserInviteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUserInviteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


