/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetThemes200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetThemes200ResponseDataInner{}

// GetThemes200ResponseDataInner struct for GetThemes200ResponseDataInner
type GetThemes200ResponseDataInner struct {
	Id string `json:"id"`
	// The name of the theme
	Name string `json:"name"`
	// Whether this theme is owned by the system (true) or by the organization (false)
	IsSystemOwned bool `json:"isSystemOwned"`
	// Primary background color (hex format)
	Background1 string `json:"background1"`
	// Secondary background color (hex format)
	Background2 string `json:"background2"`
	// Text color (hex format)
	Text string `json:"text"`
	// Primary accent color (hex format)
	Accent1 string `json:"accent1"`
	// Secondary accent color (hex format)
	Accent2 string `json:"accent2"`
	// Tertiary accent color (hex format)
	Accent3 string `json:"accent3"`
	CreatedAt *Time `json:"createdAt,omitempty"`
	UpdatedAt *Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetThemes200ResponseDataInner GetThemes200ResponseDataInner

// NewGetThemes200ResponseDataInner instantiates a new GetThemes200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetThemes200ResponseDataInner(id string, name string, isSystemOwned bool, background1 string, background2 string, text string, accent1 string, accent2 string, accent3 string) *GetThemes200ResponseDataInner {
	this := GetThemes200ResponseDataInner{}
	this.Id = id
	this.Name = name
	this.IsSystemOwned = isSystemOwned
	this.Background1 = background1
	this.Background2 = background2
	this.Text = text
	this.Accent1 = accent1
	this.Accent2 = accent2
	this.Accent3 = accent3
	return &this
}

// NewGetThemes200ResponseDataInnerWithDefaults instantiates a new GetThemes200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetThemes200ResponseDataInnerWithDefaults() *GetThemes200ResponseDataInner {
	this := GetThemes200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *GetThemes200ResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetThemes200ResponseDataInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetThemes200ResponseDataInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetThemes200ResponseDataInner) SetName(v string) {
	o.Name = v
}

// GetIsSystemOwned returns the IsSystemOwned field value
func (o *GetThemes200ResponseDataInner) GetIsSystemOwned() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSystemOwned
}

// GetIsSystemOwnedOk returns a tuple with the IsSystemOwned field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetIsSystemOwnedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSystemOwned, true
}

// SetIsSystemOwned sets field value
func (o *GetThemes200ResponseDataInner) SetIsSystemOwned(v bool) {
	o.IsSystemOwned = v
}

// GetBackground1 returns the Background1 field value
func (o *GetThemes200ResponseDataInner) GetBackground1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Background1
}

// GetBackground1Ok returns a tuple with the Background1 field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetBackground1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Background1, true
}

// SetBackground1 sets field value
func (o *GetThemes200ResponseDataInner) SetBackground1(v string) {
	o.Background1 = v
}

// GetBackground2 returns the Background2 field value
func (o *GetThemes200ResponseDataInner) GetBackground2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Background2
}

// GetBackground2Ok returns a tuple with the Background2 field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetBackground2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Background2, true
}

// SetBackground2 sets field value
func (o *GetThemes200ResponseDataInner) SetBackground2(v string) {
	o.Background2 = v
}

// GetText returns the Text field value
func (o *GetThemes200ResponseDataInner) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *GetThemes200ResponseDataInner) SetText(v string) {
	o.Text = v
}

// GetAccent1 returns the Accent1 field value
func (o *GetThemes200ResponseDataInner) GetAccent1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Accent1
}

// GetAccent1Ok returns a tuple with the Accent1 field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetAccent1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accent1, true
}

// SetAccent1 sets field value
func (o *GetThemes200ResponseDataInner) SetAccent1(v string) {
	o.Accent1 = v
}

// GetAccent2 returns the Accent2 field value
func (o *GetThemes200ResponseDataInner) GetAccent2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Accent2
}

// GetAccent2Ok returns a tuple with the Accent2 field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetAccent2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accent2, true
}

// SetAccent2 sets field value
func (o *GetThemes200ResponseDataInner) SetAccent2(v string) {
	o.Accent2 = v
}

// GetAccent3 returns the Accent3 field value
func (o *GetThemes200ResponseDataInner) GetAccent3() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Accent3
}

// GetAccent3Ok returns a tuple with the Accent3 field value
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetAccent3Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accent3, true
}

// SetAccent3 sets field value
func (o *GetThemes200ResponseDataInner) SetAccent3(v string) {
	o.Accent3 = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetThemes200ResponseDataInner) GetCreatedAt() Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetCreatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetThemes200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given Time and assigns it to the CreatedAt field.
func (o *GetThemes200ResponseDataInner) SetCreatedAt(v Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetThemes200ResponseDataInner) GetUpdatedAt() Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetThemes200ResponseDataInner) GetUpdatedAtOk() (*Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetThemes200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given Time and assigns it to the UpdatedAt field.
func (o *GetThemes200ResponseDataInner) SetUpdatedAt(v Time) {
	o.UpdatedAt = &v
}

func (o GetThemes200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetThemes200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["isSystemOwned"] = o.IsSystemOwned
	toSerialize["background1"] = o.Background1
	toSerialize["background2"] = o.Background2
	toSerialize["text"] = o.Text
	toSerialize["accent1"] = o.Accent1
	toSerialize["accent2"] = o.Accent2
	toSerialize["accent3"] = o.Accent3
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetThemes200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"isSystemOwned",
		"background1",
		"background2",
		"text",
		"accent1",
		"accent2",
		"accent3",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetThemes200ResponseDataInner := _GetThemes200ResponseDataInner{}

	err = json.Unmarshal(data, &varGetThemes200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetThemes200ResponseDataInner(varGetThemes200ResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "isSystemOwned")
		delete(additionalProperties, "background1")
		delete(additionalProperties, "background2")
		delete(additionalProperties, "text")
		delete(additionalProperties, "accent1")
		delete(additionalProperties, "accent2")
		delete(additionalProperties, "accent3")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetThemes200ResponseDataInner struct {
	value *GetThemes200ResponseDataInner
	isSet bool
}

func (v NullableGetThemes200ResponseDataInner) Get() *GetThemes200ResponseDataInner {
	return v.value
}

func (v *NullableGetThemes200ResponseDataInner) Set(val *GetThemes200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetThemes200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetThemes200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetThemes200ResponseDataInner(val *GetThemes200ResponseDataInner) *NullableGetThemes200ResponseDataInner {
	return &NullableGetThemes200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetThemes200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetThemes200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


