/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateThemeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateThemeRequest{}

// CreateThemeRequest struct for CreateThemeRequest
type CreateThemeRequest struct {
	// The name of the theme
	Name string `json:"name"`
	// Primary background color (hex format)
	Background1 string `json:"background1"`
	// Secondary background color (hex format)
	Background2 string `json:"background2"`
	// Text color (hex format)
	Text string `json:"text"`
	// Primary accent color (hex format)
	Accent1 string `json:"accent1"`
	// Secondary accent color (hex format)
	Accent2 string `json:"accent2"`
	// Tertiary accent color (hex format)
	Accent3 string `json:"accent3"`
	AdditionalProperties map[string]interface{}
}

type _CreateThemeRequest CreateThemeRequest

// NewCreateThemeRequest instantiates a new CreateThemeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateThemeRequest(name string, background1 string, background2 string, text string, accent1 string, accent2 string, accent3 string) *CreateThemeRequest {
	this := CreateThemeRequest{}
	this.Name = name
	this.Background1 = background1
	this.Background2 = background2
	this.Text = text
	this.Accent1 = accent1
	this.Accent2 = accent2
	this.Accent3 = accent3
	return &this
}

// NewCreateThemeRequestWithDefaults instantiates a new CreateThemeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateThemeRequestWithDefaults() *CreateThemeRequest {
	this := CreateThemeRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateThemeRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateThemeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateThemeRequest) SetName(v string) {
	o.Name = v
}

// GetBackground1 returns the Background1 field value
func (o *CreateThemeRequest) GetBackground1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Background1
}

// GetBackground1Ok returns a tuple with the Background1 field value
// and a boolean to check if the value has been set.
func (o *CreateThemeRequest) GetBackground1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Background1, true
}

// SetBackground1 sets field value
func (o *CreateThemeRequest) SetBackground1(v string) {
	o.Background1 = v
}

// GetBackground2 returns the Background2 field value
func (o *CreateThemeRequest) GetBackground2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Background2
}

// GetBackground2Ok returns a tuple with the Background2 field value
// and a boolean to check if the value has been set.
func (o *CreateThemeRequest) GetBackground2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Background2, true
}

// SetBackground2 sets field value
func (o *CreateThemeRequest) SetBackground2(v string) {
	o.Background2 = v
}

// GetText returns the Text field value
func (o *CreateThemeRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *CreateThemeRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *CreateThemeRequest) SetText(v string) {
	o.Text = v
}

// GetAccent1 returns the Accent1 field value
func (o *CreateThemeRequest) GetAccent1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Accent1
}

// GetAccent1Ok returns a tuple with the Accent1 field value
// and a boolean to check if the value has been set.
func (o *CreateThemeRequest) GetAccent1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accent1, true
}

// SetAccent1 sets field value
func (o *CreateThemeRequest) SetAccent1(v string) {
	o.Accent1 = v
}

// GetAccent2 returns the Accent2 field value
func (o *CreateThemeRequest) GetAccent2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Accent2
}

// GetAccent2Ok returns a tuple with the Accent2 field value
// and a boolean to check if the value has been set.
func (o *CreateThemeRequest) GetAccent2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accent2, true
}

// SetAccent2 sets field value
func (o *CreateThemeRequest) SetAccent2(v string) {
	o.Accent2 = v
}

// GetAccent3 returns the Accent3 field value
func (o *CreateThemeRequest) GetAccent3() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Accent3
}

// GetAccent3Ok returns a tuple with the Accent3 field value
// and a boolean to check if the value has been set.
func (o *CreateThemeRequest) GetAccent3Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accent3, true
}

// SetAccent3 sets field value
func (o *CreateThemeRequest) SetAccent3(v string) {
	o.Accent3 = v
}

func (o CreateThemeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateThemeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["background1"] = o.Background1
	toSerialize["background2"] = o.Background2
	toSerialize["text"] = o.Text
	toSerialize["accent1"] = o.Accent1
	toSerialize["accent2"] = o.Accent2
	toSerialize["accent3"] = o.Accent3

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateThemeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"background1",
		"background2",
		"text",
		"accent1",
		"accent2",
		"accent3",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateThemeRequest := _CreateThemeRequest{}

	err = json.Unmarshal(data, &varCreateThemeRequest)

	if err != nil {
		return err
	}

	*o = CreateThemeRequest(varCreateThemeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "background1")
		delete(additionalProperties, "background2")
		delete(additionalProperties, "text")
		delete(additionalProperties, "accent1")
		delete(additionalProperties, "accent2")
		delete(additionalProperties, "accent3")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateThemeRequest struct {
	value *CreateThemeRequest
	isSet bool
}

func (v NullableCreateThemeRequest) Get() *CreateThemeRequest {
	return v.value
}

func (v *NullableCreateThemeRequest) Set(val *CreateThemeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateThemeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateThemeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateThemeRequest(val *CreateThemeRequest) *NullableCreateThemeRequest {
	return &NullableCreateThemeRequest{value: val, isSet: true}
}

func (v NullableCreateThemeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateThemeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


