/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent{}

// ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent The content to display in kiosk mode
type ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent struct {
	// Type of kiosk content
	Type string `json:"type"`
	// UUID of the content item
	Id string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent

// NewConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent instantiates a new ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent(type_ string, id string) *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent {
	this := ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContentWithDefaults instantiates a new ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContentWithDefaults() *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent {
	this := ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent{}
	return &this
}

// GetType returns the Type field value
func (o *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) SetId(v string) {
	o.Id = v
}

func (o ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent := _ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent{}

	err = json.Unmarshal(data, &varConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent)

	if err != nil {
		return err
	}

	*o = ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent(varConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent struct {
	value *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent
	isSet bool
}

func (v NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) Get() *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent {
	return v.value
}

func (v *NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) Set(val *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent(val *ConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) *NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent {
	return &NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent{value: val, isSet: true}
}

func (v NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureGroupArborXrKioskHeadsetExperienceRequestKioskContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


