/*
ArborXR MDM API

This API provides a RESTful interface to interact with your organization's devices under management.

API version: v3
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetDevices200ResponseDataInnerControllersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDevices200ResponseDataInnerControllersInner{}

// GetDevices200ResponseDataInnerControllersInner Currently, only PICO & Meta Hms devices report this data.
type GetDevices200ResponseDataInnerControllersInner struct {
	Name string `json:"name"`
	BatteryLevel int32 `json:"batteryLevel"`
	IsConnected bool `json:"isConnected"`
	AdditionalProperties map[string]interface{}
}

type _GetDevices200ResponseDataInnerControllersInner GetDevices200ResponseDataInnerControllersInner

// NewGetDevices200ResponseDataInnerControllersInner instantiates a new GetDevices200ResponseDataInnerControllersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDevices200ResponseDataInnerControllersInner(name string, batteryLevel int32, isConnected bool) *GetDevices200ResponseDataInnerControllersInner {
	this := GetDevices200ResponseDataInnerControllersInner{}
	this.Name = name
	this.BatteryLevel = batteryLevel
	this.IsConnected = isConnected
	return &this
}

// NewGetDevices200ResponseDataInnerControllersInnerWithDefaults instantiates a new GetDevices200ResponseDataInnerControllersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDevices200ResponseDataInnerControllersInnerWithDefaults() *GetDevices200ResponseDataInnerControllersInner {
	this := GetDevices200ResponseDataInnerControllersInner{}
	return &this
}

// GetName returns the Name field value
func (o *GetDevices200ResponseDataInnerControllersInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInnerControllersInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetDevices200ResponseDataInnerControllersInner) SetName(v string) {
	o.Name = v
}

// GetBatteryLevel returns the BatteryLevel field value
func (o *GetDevices200ResponseDataInnerControllersInner) GetBatteryLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BatteryLevel
}

// GetBatteryLevelOk returns a tuple with the BatteryLevel field value
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInnerControllersInner) GetBatteryLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatteryLevel, true
}

// SetBatteryLevel sets field value
func (o *GetDevices200ResponseDataInnerControllersInner) SetBatteryLevel(v int32) {
	o.BatteryLevel = v
}

// GetIsConnected returns the IsConnected field value
func (o *GetDevices200ResponseDataInnerControllersInner) GetIsConnected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsConnected
}

// GetIsConnectedOk returns a tuple with the IsConnected field value
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInnerControllersInner) GetIsConnectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsConnected, true
}

// SetIsConnected sets field value
func (o *GetDevices200ResponseDataInnerControllersInner) SetIsConnected(v bool) {
	o.IsConnected = v
}

func (o GetDevices200ResponseDataInnerControllersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDevices200ResponseDataInnerControllersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["batteryLevel"] = o.BatteryLevel
	toSerialize["isConnected"] = o.IsConnected

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDevices200ResponseDataInnerControllersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"batteryLevel",
		"isConnected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDevices200ResponseDataInnerControllersInner := _GetDevices200ResponseDataInnerControllersInner{}

	err = json.Unmarshal(data, &varGetDevices200ResponseDataInnerControllersInner)

	if err != nil {
		return err
	}

	*o = GetDevices200ResponseDataInnerControllersInner(varGetDevices200ResponseDataInnerControllersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "batteryLevel")
		delete(additionalProperties, "isConnected")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDevices200ResponseDataInnerControllersInner struct {
	value *GetDevices200ResponseDataInnerControllersInner
	isSet bool
}

func (v NullableGetDevices200ResponseDataInnerControllersInner) Get() *GetDevices200ResponseDataInnerControllersInner {
	return v.value
}

func (v *NullableGetDevices200ResponseDataInnerControllersInner) Set(val *GetDevices200ResponseDataInnerControllersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDevices200ResponseDataInnerControllersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDevices200ResponseDataInnerControllersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDevices200ResponseDataInnerControllersInner(val *GetDevices200ResponseDataInnerControllersInner) *NullableGetDevices200ResponseDataInnerControllersInner {
	return &NullableGetDevices200ResponseDataInnerControllersInner{value: val, isSet: true}
}

func (v NullableGetDevices200ResponseDataInnerControllersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDevices200ResponseDataInnerControllersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


